// Auto-generated by claw402 codegen — DO NOT EDIT
// Provider: Alpaca Markets (alpaca)

package claw402

import (
	"context"
	"encoding/json"
)

// AlpacaQuotes provides methods for Alpaca quotes endpoints.
type AlpacaQuotes struct {
	client *Client
}

// AlpacaQuotesLatestParams are the query parameters for Latest.
type AlpacaQuotesLatestParams struct {
	Symbols string `json:"symbols,omitempty"`
	Feed string `json:"feed,omitempty"`
	Currency string `json:"currency,omitempty"`
}

// Latest quote for one or more US stocks — $0.001/call
func (r *AlpacaQuotes) Latest(ctx context.Context, params *AlpacaQuotesLatestParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbols != "" {
		q["symbols"] = params.Symbols
	}
	if params != nil && params.Feed != "" {
		q["feed"] = params.Feed
	}
	if params != nil && params.Currency != "" {
		q["currency"] = params.Currency
	}
	return r.client.get(ctx, "/api/v1/alpaca/quotes/latest", q)
}

// AlpacaQuotesHistoryParams are the query parameters for History.
type AlpacaQuotesHistoryParams struct {
	Symbols string `json:"symbols,omitempty"`
	Start string `json:"start,omitempty"`
	End string `json:"end,omitempty"`
	Limit string `json:"limit,omitempty"`
	Feed string `json:"feed,omitempty"`
	Sort string `json:"sort,omitempty"`
}

// Historical tick-level quotes for US stocks — $0.002/call
func (r *AlpacaQuotes) History(ctx context.Context, params *AlpacaQuotesHistoryParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbols != "" {
		q["symbols"] = params.Symbols
	}
	if params != nil && params.Start != "" {
		q["start"] = params.Start
	}
	if params != nil && params.End != "" {
		q["end"] = params.End
	}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	if params != nil && params.Feed != "" {
		q["feed"] = params.Feed
	}
	if params != nil && params.Sort != "" {
		q["sort"] = params.Sort
	}
	return r.client.get(ctx, "/api/v1/alpaca/quotes/history", q)
}

// AlpacaBars provides methods for Alpaca bars endpoints.
type AlpacaBars struct {
	client *Client
}

// AlpacaBarsLatestParams are the query parameters for Latest.
type AlpacaBarsLatestParams struct {
	Symbols string `json:"symbols,omitempty"`
	Feed string `json:"feed,omitempty"`
	Currency string `json:"currency,omitempty"`
}

// Latest bar for US stocks — $0.001/call
func (r *AlpacaBars) Latest(ctx context.Context, params *AlpacaBarsLatestParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbols != "" {
		q["symbols"] = params.Symbols
	}
	if params != nil && params.Feed != "" {
		q["feed"] = params.Feed
	}
	if params != nil && params.Currency != "" {
		q["currency"] = params.Currency
	}
	return r.client.get(ctx, "/api/v1/alpaca/bars/latest", q)
}

// AlpacaTrades provides methods for Alpaca trades endpoints.
type AlpacaTrades struct {
	client *Client
}

// AlpacaTradesLatestParams are the query parameters for Latest.
type AlpacaTradesLatestParams struct {
	Symbols string `json:"symbols,omitempty"`
	Feed string `json:"feed,omitempty"`
	Currency string `json:"currency,omitempty"`
}

// Latest trade for US stocks — $0.001/call
func (r *AlpacaTrades) Latest(ctx context.Context, params *AlpacaTradesLatestParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbols != "" {
		q["symbols"] = params.Symbols
	}
	if params != nil && params.Feed != "" {
		q["feed"] = params.Feed
	}
	if params != nil && params.Currency != "" {
		q["currency"] = params.Currency
	}
	return r.client.get(ctx, "/api/v1/alpaca/trades/latest", q)
}

// AlpacaTradesHistoryParams are the query parameters for History.
type AlpacaTradesHistoryParams struct {
	Symbols string `json:"symbols,omitempty"`
	Start string `json:"start,omitempty"`
	End string `json:"end,omitempty"`
	Limit string `json:"limit,omitempty"`
	Feed string `json:"feed,omitempty"`
	Sort string `json:"sort,omitempty"`
}

// Historical trades for US stocks — $0.002/call
func (r *AlpacaTrades) History(ctx context.Context, params *AlpacaTradesHistoryParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbols != "" {
		q["symbols"] = params.Symbols
	}
	if params != nil && params.Start != "" {
		q["start"] = params.Start
	}
	if params != nil && params.End != "" {
		q["end"] = params.End
	}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	if params != nil && params.Feed != "" {
		q["feed"] = params.Feed
	}
	if params != nil && params.Sort != "" {
		q["sort"] = params.Sort
	}
	return r.client.get(ctx, "/api/v1/alpaca/trades/history", q)
}

// AlpacaOptions provides methods for Alpaca options endpoints.
type AlpacaOptions struct {
	client *Client
}

// AlpacaOptionsBarsParams are the query parameters for Bars.
type AlpacaOptionsBarsParams struct {
	Symbols string `json:"symbols,omitempty"`
	Timeframe string `json:"timeframe,omitempty"`
	Start string `json:"start,omitempty"`
	End string `json:"end,omitempty"`
	Limit string `json:"limit,omitempty"`
}

// Historical OHLCV bars for options contracts — $0.003/call
func (r *AlpacaOptions) Bars(ctx context.Context, params *AlpacaOptionsBarsParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbols != "" {
		q["symbols"] = params.Symbols
	}
	if params != nil && params.Timeframe != "" {
		q["timeframe"] = params.Timeframe
	}
	if params != nil && params.Start != "" {
		q["start"] = params.Start
	}
	if params != nil && params.End != "" {
		q["end"] = params.End
	}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	return r.client.get(ctx, "/api/v1/alpaca/options/bars", q)
}

// AlpacaOptionsQuotesLatestParams are the query parameters for QuotesLatest.
type AlpacaOptionsQuotesLatestParams struct {
	Symbols string `json:"symbols,omitempty"`
	Feed string `json:"feed,omitempty"`
}

// Latest quotes for options contracts — $0.003/call
func (r *AlpacaOptions) QuotesLatest(ctx context.Context, params *AlpacaOptionsQuotesLatestParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbols != "" {
		q["symbols"] = params.Symbols
	}
	if params != nil && params.Feed != "" {
		q["feed"] = params.Feed
	}
	return r.client.get(ctx, "/api/v1/alpaca/options/quotes/latest", q)
}

// AlpacaOptionsSnapshotsParams are the query parameters for Snapshots.
type AlpacaOptionsSnapshotsParams struct {
	Symbols string `json:"symbols,omitempty"`
	Feed string `json:"feed,omitempty"`
}

// Snapshots for options contracts — $0.003/call
func (r *AlpacaOptions) Snapshots(ctx context.Context, params *AlpacaOptionsSnapshotsParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbols != "" {
		q["symbols"] = params.Symbols
	}
	if params != nil && params.Feed != "" {
		q["feed"] = params.Feed
	}
	return r.client.get(ctx, "/api/v1/alpaca/options/snapshots", q)
}

// AlpacaResource provides access to all Alpaca Markets API endpoints.
type AlpacaResource struct {
	client *Client
	Quotes *AlpacaQuotes
	Bars *AlpacaBars
	Trades *AlpacaTrades
	Options *AlpacaOptions
}

func newAlpacaResource(c *Client) *AlpacaResource {
	return &AlpacaResource{
		client: c,
		Quotes: &AlpacaQuotes{client: c},
		Bars: &AlpacaBars{client: c},
		Trades: &AlpacaTrades{client: c},
		Options: &AlpacaOptions{client: c},
	}
}

// AlpacaGetBarsParams are the query parameters for GetBars.
type AlpacaGetBarsParams struct {
	Symbols string `json:"symbols,omitempty"`
	Timeframe string `json:"timeframe,omitempty"`
	Start string `json:"start,omitempty"`
	End string `json:"end,omitempty"`
	Limit string `json:"limit,omitempty"`
	Adjustment string `json:"adjustment,omitempty"`
	Feed string `json:"feed,omitempty"`
	Sort string `json:"sort,omitempty"`
}

// Historical OHLCV bars for US stocks — $0.001/call
func (r *AlpacaResource) GetBars(ctx context.Context, params *AlpacaGetBarsParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbols != "" {
		q["symbols"] = params.Symbols
	}
	if params != nil && params.Timeframe != "" {
		q["timeframe"] = params.Timeframe
	}
	if params != nil && params.Start != "" {
		q["start"] = params.Start
	}
	if params != nil && params.End != "" {
		q["end"] = params.End
	}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	if params != nil && params.Adjustment != "" {
		q["adjustment"] = params.Adjustment
	}
	if params != nil && params.Feed != "" {
		q["feed"] = params.Feed
	}
	if params != nil && params.Sort != "" {
		q["sort"] = params.Sort
	}
	return r.client.get(ctx, "/api/v1/alpaca/bars", q)
}

// AlpacaSnapshotsParams are the query parameters for Snapshots.
type AlpacaSnapshotsParams struct {
	Symbols string `json:"symbols,omitempty"`
	Feed string `json:"feed,omitempty"`
	Currency string `json:"currency,omitempty"`
}

// Full market snapshot with quote, trade, minute/daily bar and prev close — $0.002/call
func (r *AlpacaResource) Snapshots(ctx context.Context, params *AlpacaSnapshotsParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbols != "" {
		q["symbols"] = params.Symbols
	}
	if params != nil && params.Feed != "" {
		q["feed"] = params.Feed
	}
	if params != nil && params.Currency != "" {
		q["currency"] = params.Currency
	}
	return r.client.get(ctx, "/api/v1/alpaca/snapshots", q)
}

// AlpacaSnapshotParams are the query parameters for Snapshot.
type AlpacaSnapshotParams struct {
	Symbols string `json:"symbols,omitempty"`
	Feed string `json:"feed,omitempty"`
	Currency string `json:"currency,omitempty"`
}

// Snapshot for a single US stock — $0.001/call
func (r *AlpacaResource) Snapshot(ctx context.Context, params *AlpacaSnapshotParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbols != "" {
		q["symbols"] = params.Symbols
	}
	if params != nil && params.Feed != "" {
		q["feed"] = params.Feed
	}
	if params != nil && params.Currency != "" {
		q["currency"] = params.Currency
	}
	return r.client.get(ctx, "/api/v1/alpaca/snapshot", q)
}

// AlpacaMoversParams are the query parameters for Movers.
type AlpacaMoversParams struct {
	Top string `json:"top,omitempty"`
	MarketType string `json:"market_type,omitempty"`
}

// Top market movers by percentage change — $0.002/call
func (r *AlpacaResource) Movers(ctx context.Context, params *AlpacaMoversParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Top != "" {
		q["top"] = params.Top
	}
	if params != nil && params.MarketType != "" {
		q["market_type"] = params.MarketType
	}
	return r.client.get(ctx, "/api/v1/alpaca/movers", q)
}

// AlpacaMostActivesParams are the query parameters for MostActives.
type AlpacaMostActivesParams struct {
	Top string `json:"top,omitempty"`
	MarketType string `json:"market_type,omitempty"`
}

// Most active stocks by volume — $0.002/call
func (r *AlpacaResource) MostActives(ctx context.Context, params *AlpacaMostActivesParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Top != "" {
		q["top"] = params.Top
	}
	if params != nil && params.MarketType != "" {
		q["market_type"] = params.MarketType
	}
	return r.client.get(ctx, "/api/v1/alpaca/most-actives", q)
}

// AlpacaNewsParams are the query parameters for News.
type AlpacaNewsParams struct {
	Symbols string `json:"symbols,omitempty"`
	Start string `json:"start,omitempty"`
	End string `json:"end,omitempty"`
	Limit string `json:"limit,omitempty"`
	Sort string `json:"sort,omitempty"`
	IncludeContent string `json:"include_content,omitempty"`
}

// Real-time financial news for US stocks — $0.002/call
func (r *AlpacaResource) News(ctx context.Context, params *AlpacaNewsParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbols != "" {
		q["symbols"] = params.Symbols
	}
	if params != nil && params.Start != "" {
		q["start"] = params.Start
	}
	if params != nil && params.End != "" {
		q["end"] = params.End
	}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	if params != nil && params.Sort != "" {
		q["sort"] = params.Sort
	}
	if params != nil && params.IncludeContent != "" {
		q["include_content"] = params.IncludeContent
	}
	return r.client.get(ctx, "/api/v1/alpaca/news", q)
}

// AlpacaCorporateActionsParams are the query parameters for CorporateActions.
type AlpacaCorporateActionsParams struct {
	Symbols string `json:"symbols,omitempty"`
	Types string `json:"types,omitempty"`
	Start string `json:"start,omitempty"`
	End string `json:"end,omitempty"`
	Limit string `json:"limit,omitempty"`
	Sort string `json:"sort,omitempty"`
}

// Corporate action events (dividends, splits, etc.) — $0.002/call
func (r *AlpacaResource) CorporateActions(ctx context.Context, params *AlpacaCorporateActionsParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbols != "" {
		q["symbols"] = params.Symbols
	}
	if params != nil && params.Types != "" {
		q["types"] = params.Types
	}
	if params != nil && params.Start != "" {
		q["start"] = params.Start
	}
	if params != nil && params.End != "" {
		q["end"] = params.End
	}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	if params != nil && params.Sort != "" {
		q["sort"] = params.Sort
	}
	return r.client.get(ctx, "/api/v1/alpaca/corporate-actions", q)
}
