// Auto-generated by claw402 codegen — DO NOT EDIT
// Provider: Alpha Vantage (alphavantage)

package claw402

import (
	"context"
	"encoding/json"
)

// AlphavantageUs provides methods for Alphavantage us endpoints.
type AlphavantageUs struct {
	client *Client
}

// AlphavantageUsQuoteParams are the query parameters for Quote.
type AlphavantageUsQuoteParams struct {
	Symbol string `json:"symbol,omitempty"`
}

// Real-time US stock quote (price, change, volume) — $0.001/call
func (r *AlphavantageUs) Quote(ctx context.Context, params *AlphavantageUsQuoteParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	return r.client.get(ctx, "/api/v1/stocks/us/quote", q)
}

// AlphavantageUsSearchParams are the query parameters for Search.
type AlphavantageUsSearchParams struct {
	Keywords string `json:"keywords,omitempty"`
}

// Stock symbol search by keyword — $0.001/call
func (r *AlphavantageUs) Search(ctx context.Context, params *AlphavantageUsSearchParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Keywords != "" {
		q["keywords"] = params.Keywords
	}
	return r.client.get(ctx, "/api/v1/stocks/us/search", q)
}

// AlphavantageUsDailyParams are the query parameters for Daily.
type AlphavantageUsDailyParams struct {
	Symbol string `json:"symbol,omitempty"`
	Outputsize string `json:"outputsize,omitempty"`
	Datatype string `json:"datatype,omitempty"`
}

// Daily OHLCV data (compact=100 days or full history) — $0.001/call
func (r *AlphavantageUs) Daily(ctx context.Context, params *AlphavantageUsDailyParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	if params != nil && params.Outputsize != "" {
		q["outputsize"] = params.Outputsize
	}
	if params != nil && params.Datatype != "" {
		q["datatype"] = params.Datatype
	}
	return r.client.get(ctx, "/api/v1/stocks/us/daily", q)
}

// AlphavantageUsDailyAdjustedParams are the query parameters for DailyAdjusted.
type AlphavantageUsDailyAdjustedParams struct {
	Symbol string `json:"symbol,omitempty"`
	Outputsize string `json:"outputsize,omitempty"`
	Datatype string `json:"datatype,omitempty"`
}

// Daily adjusted OHLCV (dividend & split adjusted) — $0.001/call
func (r *AlphavantageUs) DailyAdjusted(ctx context.Context, params *AlphavantageUsDailyAdjustedParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	if params != nil && params.Outputsize != "" {
		q["outputsize"] = params.Outputsize
	}
	if params != nil && params.Datatype != "" {
		q["datatype"] = params.Datatype
	}
	return r.client.get(ctx, "/api/v1/stocks/us/daily-adjusted", q)
}

// AlphavantageUsIntradayParams are the query parameters for Intraday.
type AlphavantageUsIntradayParams struct {
	Symbol string `json:"symbol,omitempty"`
	Interval string `json:"interval,omitempty"`
	Outputsize string `json:"outputsize,omitempty"`
	Month string `json:"month,omitempty"`
}

// Intraday OHLCV bars (1/5/15/30/60min intervals) — $0.001/call
func (r *AlphavantageUs) Intraday(ctx context.Context, params *AlphavantageUsIntradayParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	if params != nil && params.Interval != "" {
		q["interval"] = params.Interval
	}
	if params != nil && params.Outputsize != "" {
		q["outputsize"] = params.Outputsize
	}
	if params != nil && params.Month != "" {
		q["month"] = params.Month
	}
	return r.client.get(ctx, "/api/v1/stocks/us/intraday", q)
}

// AlphavantageUsWeeklyParams are the query parameters for Weekly.
type AlphavantageUsWeeklyParams struct {
	Symbol string `json:"symbol,omitempty"`
}

// Weekly OHLCV time series — $0.001/call
func (r *AlphavantageUs) Weekly(ctx context.Context, params *AlphavantageUsWeeklyParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	return r.client.get(ctx, "/api/v1/stocks/us/weekly", q)
}

// AlphavantageUsMonthlyParams are the query parameters for Monthly.
type AlphavantageUsMonthlyParams struct {
	Symbol string `json:"symbol,omitempty"`
}

// Monthly OHLCV time series — $0.001/call
func (r *AlphavantageUs) Monthly(ctx context.Context, params *AlphavantageUsMonthlyParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	return r.client.get(ctx, "/api/v1/stocks/us/monthly", q)
}

// AlphavantageUsOverviewParams are the query parameters for Overview.
type AlphavantageUsOverviewParams struct {
	Symbol string `json:"symbol,omitempty"`
}

// Company overview: market cap, PE, PB, revenue, EPS, dividends — $0.001/call
func (r *AlphavantageUs) Overview(ctx context.Context, params *AlphavantageUsOverviewParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	return r.client.get(ctx, "/api/v1/stocks/us/overview", q)
}

// AlphavantageUsEarningsParams are the query parameters for Earnings.
type AlphavantageUsEarningsParams struct {
	Symbol string `json:"symbol,omitempty"`
}

// Quarterly & annual EPS vs. analyst estimates — $0.001/call
func (r *AlphavantageUs) Earnings(ctx context.Context, params *AlphavantageUsEarningsParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	return r.client.get(ctx, "/api/v1/stocks/us/earnings", q)
}

// AlphavantageUsIncomeParams are the query parameters for Income.
type AlphavantageUsIncomeParams struct {
	Symbol string `json:"symbol,omitempty"`
}

// Income statement (quarterly & annual) — $0.001/call
func (r *AlphavantageUs) Income(ctx context.Context, params *AlphavantageUsIncomeParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	return r.client.get(ctx, "/api/v1/stocks/us/income", q)
}

// AlphavantageUsBalanceSheetParams are the query parameters for BalanceSheet.
type AlphavantageUsBalanceSheetParams struct {
	Symbol string `json:"symbol,omitempty"`
}

// Balance sheet (quarterly & annual) — $0.001/call
func (r *AlphavantageUs) BalanceSheet(ctx context.Context, params *AlphavantageUsBalanceSheetParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	return r.client.get(ctx, "/api/v1/stocks/us/balance-sheet", q)
}

// AlphavantageUsCashFlowParams are the query parameters for CashFlow.
type AlphavantageUsCashFlowParams struct {
	Symbol string `json:"symbol,omitempty"`
}

// Cash flow statement (quarterly & annual) — $0.001/call
func (r *AlphavantageUs) CashFlow(ctx context.Context, params *AlphavantageUsCashFlowParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	return r.client.get(ctx, "/api/v1/stocks/us/cash-flow", q)
}

// Top gainers, losers, and most active stocks today — $0.001/call
func (r *AlphavantageUs) Movers(ctx context.Context) (json.RawMessage, error) {
	return r.client.get(ctx, "/api/v1/stocks/us/movers", nil)
}

// AlphavantageUsNewsParams are the query parameters for News.
type AlphavantageUsNewsParams struct {
	Tickers string `json:"tickers,omitempty"`
	Topics string `json:"topics,omitempty"`
	TimeFrom string `json:"time_from,omitempty"`
	TimeTo string `json:"time_to,omitempty"`
	Sort string `json:"sort,omitempty"`
	Limit string `json:"limit,omitempty"`
}

// News articles with AI sentiment scores (bullish/bearish) — $0.001/call
func (r *AlphavantageUs) News(ctx context.Context, params *AlphavantageUsNewsParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Tickers != "" {
		q["tickers"] = params.Tickers
	}
	if params != nil && params.Topics != "" {
		q["topics"] = params.Topics
	}
	if params != nil && params.TimeFrom != "" {
		q["time_from"] = params.TimeFrom
	}
	if params != nil && params.TimeTo != "" {
		q["time_to"] = params.TimeTo
	}
	if params != nil && params.Sort != "" {
		q["sort"] = params.Sort
	}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	return r.client.get(ctx, "/api/v1/stocks/us/news", q)
}

// AlphavantageUsRsiParams are the query parameters for Rsi.
type AlphavantageUsRsiParams struct {
	Symbol string `json:"symbol,omitempty"`
	Interval string `json:"interval,omitempty"`
	TimePeriod string `json:"time_period,omitempty"`
	SeriesType string `json:"series_type,omitempty"`
}

// Relative Strength Index (RSI) — $0.001/call
func (r *AlphavantageUs) Rsi(ctx context.Context, params *AlphavantageUsRsiParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	if params != nil && params.Interval != "" {
		q["interval"] = params.Interval
	}
	if params != nil && params.TimePeriod != "" {
		q["time_period"] = params.TimePeriod
	}
	if params != nil && params.SeriesType != "" {
		q["series_type"] = params.SeriesType
	}
	return r.client.get(ctx, "/api/v1/stocks/us/rsi", q)
}

// AlphavantageUsMacdParams are the query parameters for Macd.
type AlphavantageUsMacdParams struct {
	Symbol string `json:"symbol,omitempty"`
	Interval string `json:"interval,omitempty"`
	SeriesType string `json:"series_type,omitempty"`
	Fastperiod string `json:"fastperiod,omitempty"`
	Slowperiod string `json:"slowperiod,omitempty"`
	Signalperiod string `json:"signalperiod,omitempty"`
}

// MACD (signal, histogram, fast/slow lines) — $0.001/call
func (r *AlphavantageUs) Macd(ctx context.Context, params *AlphavantageUsMacdParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	if params != nil && params.Interval != "" {
		q["interval"] = params.Interval
	}
	if params != nil && params.SeriesType != "" {
		q["series_type"] = params.SeriesType
	}
	if params != nil && params.Fastperiod != "" {
		q["fastperiod"] = params.Fastperiod
	}
	if params != nil && params.Slowperiod != "" {
		q["slowperiod"] = params.Slowperiod
	}
	if params != nil && params.Signalperiod != "" {
		q["signalperiod"] = params.Signalperiod
	}
	return r.client.get(ctx, "/api/v1/stocks/us/macd", q)
}

// AlphavantageUsBbandsParams are the query parameters for Bbands.
type AlphavantageUsBbandsParams struct {
	Symbol string `json:"symbol,omitempty"`
	Interval string `json:"interval,omitempty"`
	TimePeriod string `json:"time_period,omitempty"`
	SeriesType string `json:"series_type,omitempty"`
	Nbdevup string `json:"nbdevup,omitempty"`
	Nbdevdn string `json:"nbdevdn,omitempty"`
}

// Bollinger Bands (upper, middle, lower) — $0.001/call
func (r *AlphavantageUs) Bbands(ctx context.Context, params *AlphavantageUsBbandsParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	if params != nil && params.Interval != "" {
		q["interval"] = params.Interval
	}
	if params != nil && params.TimePeriod != "" {
		q["time_period"] = params.TimePeriod
	}
	if params != nil && params.SeriesType != "" {
		q["series_type"] = params.SeriesType
	}
	if params != nil && params.Nbdevup != "" {
		q["nbdevup"] = params.Nbdevup
	}
	if params != nil && params.Nbdevdn != "" {
		q["nbdevdn"] = params.Nbdevdn
	}
	return r.client.get(ctx, "/api/v1/stocks/us/bbands", q)
}

// AlphavantageUsSmaParams are the query parameters for Sma.
type AlphavantageUsSmaParams struct {
	Symbol string `json:"symbol,omitempty"`
	Interval string `json:"interval,omitempty"`
	TimePeriod string `json:"time_period,omitempty"`
	SeriesType string `json:"series_type,omitempty"`
}

// Simple Moving Average (SMA) — $0.001/call
func (r *AlphavantageUs) Sma(ctx context.Context, params *AlphavantageUsSmaParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	if params != nil && params.Interval != "" {
		q["interval"] = params.Interval
	}
	if params != nil && params.TimePeriod != "" {
		q["time_period"] = params.TimePeriod
	}
	if params != nil && params.SeriesType != "" {
		q["series_type"] = params.SeriesType
	}
	return r.client.get(ctx, "/api/v1/stocks/us/sma", q)
}

// AlphavantageUsEmaParams are the query parameters for Ema.
type AlphavantageUsEmaParams struct {
	Symbol string `json:"symbol,omitempty"`
	Interval string `json:"interval,omitempty"`
	TimePeriod string `json:"time_period,omitempty"`
	SeriesType string `json:"series_type,omitempty"`
}

// Exponential Moving Average (EMA) — $0.001/call
func (r *AlphavantageUs) Ema(ctx context.Context, params *AlphavantageUsEmaParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	if params != nil && params.Interval != "" {
		q["interval"] = params.Interval
	}
	if params != nil && params.TimePeriod != "" {
		q["time_period"] = params.TimePeriod
	}
	if params != nil && params.SeriesType != "" {
		q["series_type"] = params.SeriesType
	}
	return r.client.get(ctx, "/api/v1/stocks/us/ema", q)
}

// AlphavantageResource provides access to all Alpha Vantage API endpoints.
type AlphavantageResource struct {
	client *Client
	Us *AlphavantageUs
}

func newAlphavantageResource(c *Client) *AlphavantageResource {
	return &AlphavantageResource{
		client: c,
		Us: &AlphavantageUs{client: c},
	}
}


