// Auto-generated by claw402 codegen — DO NOT EDIT
// Provider: Anthropic (anthropic)

package claw402

import (
	"context"
	"encoding/json"
)

// AnthropicAnthropic provides methods for Anthropic anthropic endpoints.
type AnthropicAnthropic struct {
	client *Client
}

// Messages API with Claude Sonnet (default) — $0.01/call
func (r *AnthropicAnthropic) Messages(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/ai/anthropic/messages", body)
}

// Messages API with Claude Haiku (faster, cheaper) — $0.003/call
func (r *AnthropicAnthropic) MessagesHaiku(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/ai/anthropic/messages/haiku", body)
}

// Messages API with Claude Opus (strongest reasoning) — $0.05/call
func (r *AnthropicAnthropic) MessagesOpus(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/ai/anthropic/messages/opus", body)
}

// AnthropicResource provides access to all Anthropic API endpoints.
type AnthropicResource struct {
	client *Client
	Anthropic *AnthropicAnthropic
}

func newAnthropicResource(c *Client) *AnthropicResource {
	return &AnthropicResource{
		client: c,
		Anthropic: &AnthropicAnthropic{client: c},
	}
}


