// Auto-generated by claw402 codegen — DO NOT EDIT
// Provider: CoinMarketCap (coinmarketcap)

package claw402

import (
	"context"
	"encoding/json"
)

// CoinmarketcapCmc provides methods for Coinmarketcap cmc endpoints.
type CoinmarketcapCmc struct {
	client *Client
}

// CoinmarketcapCmcQuotesParams are the query parameters for Quotes.
type CoinmarketcapCmcQuotesParams struct {
	Id string `json:"id,omitempty"`
	Slug string `json:"slug,omitempty"`
	Symbol string `json:"symbol,omitempty"`
	Convert string `json:"convert,omitempty"`
	ConvertId string `json:"convert_id,omitempty"`
	Aux string `json:"aux,omitempty"`
	SkipInvalid string `json:"skip_invalid,omitempty"`
}

// Real-time cryptocurrency quotes. Returns price, market cap, 24h volume, % changes. Must provide at least one of id/slug/symbol. id: CMC IDs comma-separated, e.g. "1,1027" (1=BTC, 1027=ETH). slug: slugs comma-separated, e.g. "bitcoin,ethereum". symbol: ticker symbols, e.g. "BTC,ETH" (returns highest market cap if ambiguous). convert: target currencies, e.g. "USD,BTC,CNY" (up to 120). convert_id: target currencies by CMC ID, e.g. "1,2781". aux: supplemental fields (comma-separated): num_market_pairs, cmc_rank, date_added, tags, platform, max_supply, circulating_supply, total_supply, market_cap_by_total_supply, volume_24h_reported, volume_7d, volume_7d_reported, volume_30d, volume_30d_reported, is_active, is_fiat. skip_invalid: boolean, true to skip invalid IDs (default false). — $0.015/call
func (r *CoinmarketcapCmc) Quotes(ctx context.Context, params *CoinmarketcapCmcQuotesParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Id != "" {
		q["id"] = params.Id
	}
	if params != nil && params.Slug != "" {
		q["slug"] = params.Slug
	}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	if params != nil && params.Convert != "" {
		q["convert"] = params.Convert
	}
	if params != nil && params.ConvertId != "" {
		q["convert_id"] = params.ConvertId
	}
	if params != nil && params.Aux != "" {
		q["aux"] = params.Aux
	}
	if params != nil && params.SkipInvalid != "" {
		q["skip_invalid"] = params.SkipInvalid
	}
	return r.client.get(ctx, "/api/v1/crypto/cmc/quotes", q)
}

// CoinmarketcapCmcListingsParams are the query parameters for Listings.
type CoinmarketcapCmcListingsParams struct {
	Start string `json:"start,omitempty"`
	Limit string `json:"limit,omitempty"`
	PriceMin string `json:"price_min,omitempty"`
	PriceMax string `json:"price_max,omitempty"`
	MarketCapMin string `json:"market_cap_min,omitempty"`
	MarketCapMax string `json:"market_cap_max,omitempty"`
	Volume24hMin string `json:"volume_24h_min,omitempty"`
	Volume24hMax string `json:"volume_24h_max,omitempty"`
	CirculatingSupplyMin string `json:"circulating_supply_min,omitempty"`
	CirculatingSupplyMax string `json:"circulating_supply_max,omitempty"`
	PercentChange24hMin string `json:"percent_change_24h_min,omitempty"`
	PercentChange24hMax string `json:"percent_change_24h_max,omitempty"`
	Convert string `json:"convert,omitempty"`
	ConvertId string `json:"convert_id,omitempty"`
	Sort string `json:"sort,omitempty"`
	SortDir string `json:"sort_dir,omitempty"`
	CryptocurrencyType string `json:"cryptocurrency_type,omitempty"`
	Tag string `json:"tag,omitempty"`
	Aux string `json:"aux,omitempty"`
}

// Cryptocurrency rankings (default sorted by market cap). start: pagination offset, 1-based (default 1). limit: results per page, 1-5000 (default 100). price_min / price_max: filter by USD price. market_cap_min / market_cap_max: filter by market cap. volume_24h_min / volume_24h_max: filter by 24h volume. circulating_supply_min / circulating_supply_max: filter by circulating supply. percent_change_24h_min / percent_change_24h_max: filter by 24h % change. convert: target currencies, e.g. "USD,CNY". convert_id: target currencies by CMC ID. sort: sort field — name, symbol, date_added, market_cap, market_cap_strict, price, circulating_supply, total_supply, max_supply, num_market_pairs, volume_24h, percent_change_1h, percent_change_24h, percent_change_7d (default market_cap). sort_dir: asc / desc. cryptocurrency_type: all / coins / tokens (default all). tag: filter by tag, e.g. defi, filesharing. aux: supplemental data fields. — $0.015/call
func (r *CoinmarketcapCmc) Listings(ctx context.Context, params *CoinmarketcapCmcListingsParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Start != "" {
		q["start"] = params.Start
	}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	if params != nil && params.PriceMin != "" {
		q["price_min"] = params.PriceMin
	}
	if params != nil && params.PriceMax != "" {
		q["price_max"] = params.PriceMax
	}
	if params != nil && params.MarketCapMin != "" {
		q["market_cap_min"] = params.MarketCapMin
	}
	if params != nil && params.MarketCapMax != "" {
		q["market_cap_max"] = params.MarketCapMax
	}
	if params != nil && params.Volume24hMin != "" {
		q["volume_24h_min"] = params.Volume24hMin
	}
	if params != nil && params.Volume24hMax != "" {
		q["volume_24h_max"] = params.Volume24hMax
	}
	if params != nil && params.CirculatingSupplyMin != "" {
		q["circulating_supply_min"] = params.CirculatingSupplyMin
	}
	if params != nil && params.CirculatingSupplyMax != "" {
		q["circulating_supply_max"] = params.CirculatingSupplyMax
	}
	if params != nil && params.PercentChange24hMin != "" {
		q["percent_change_24h_min"] = params.PercentChange24hMin
	}
	if params != nil && params.PercentChange24hMax != "" {
		q["percent_change_24h_max"] = params.PercentChange24hMax
	}
	if params != nil && params.Convert != "" {
		q["convert"] = params.Convert
	}
	if params != nil && params.ConvertId != "" {
		q["convert_id"] = params.ConvertId
	}
	if params != nil && params.Sort != "" {
		q["sort"] = params.Sort
	}
	if params != nil && params.SortDir != "" {
		q["sort_dir"] = params.SortDir
	}
	if params != nil && params.CryptocurrencyType != "" {
		q["cryptocurrency_type"] = params.CryptocurrencyType
	}
	if params != nil && params.Tag != "" {
		q["tag"] = params.Tag
	}
	if params != nil && params.Aux != "" {
		q["aux"] = params.Aux
	}
	return r.client.get(ctx, "/api/v1/crypto/cmc/listings", q)
}

// CoinmarketcapCmcDexPairsParams are the query parameters for DexPairs.
type CoinmarketcapCmcDexPairsParams struct {
	NetworkSlug string `json:"network_slug,omitempty"`
	ContractAddress string `json:"contract_address,omitempty"`
	Sort string `json:"sort,omitempty"`
	SortDir string `json:"sort_dir,omitempty"`
	Start string `json:"start,omitempty"`
	Limit string `json:"limit,omitempty"`
	LiquidityMin string `json:"liquidity_min,omitempty"`
	Volume24hMin string `json:"volume_24h_min,omitempty"`
	Aux string `json:"aux,omitempty"`
}

// DEX trading pair real-time quotes. Query on-chain DEX pairs by contract or network. network_slug: blockchain network, e.g. "ethereum", "bsc", "solana", "base", "arbitrum". contract_address: pair or token contract address. sort: sort field. sort_dir: sort direction asc/desc. start: pagination offset (default 1). limit: results per page (default 100). liquidity_min: minimum liquidity filter. volume_24h_min: minimum 24h volume filter. aux: supplemental data fields. — $0.015/call
func (r *CoinmarketcapCmc) DexPairs(ctx context.Context, params *CoinmarketcapCmcDexPairsParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.NetworkSlug != "" {
		q["network_slug"] = params.NetworkSlug
	}
	if params != nil && params.ContractAddress != "" {
		q["contract_address"] = params.ContractAddress
	}
	if params != nil && params.Sort != "" {
		q["sort"] = params.Sort
	}
	if params != nil && params.SortDir != "" {
		q["sort_dir"] = params.SortDir
	}
	if params != nil && params.Start != "" {
		q["start"] = params.Start
	}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	if params != nil && params.LiquidityMin != "" {
		q["liquidity_min"] = params.LiquidityMin
	}
	if params != nil && params.Volume24hMin != "" {
		q["volume_24h_min"] = params.Volume24hMin
	}
	if params != nil && params.Aux != "" {
		q["aux"] = params.Aux
	}
	return r.client.get(ctx, "/api/v1/crypto/cmc/dex/pairs", q)
}

// CoinmarketcapCmcDexSearchParams are the query parameters for DexSearch.
type CoinmarketcapCmcDexSearchParams struct {
	Query string `json:"query,omitempty"`
	Network string `json:"network,omitempty"`
}

// Search DEX tokens and trading pairs by keyword. query (required): search keyword, e.g. "PEPE", "uniswap", or contract address. network: filter by blockchain network, e.g. "ethereum", "bsc", "solana". — $0.015/call
func (r *CoinmarketcapCmc) DexSearch(ctx context.Context, params *CoinmarketcapCmcDexSearchParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Query != "" {
		q["query"] = params.Query
	}
	if params != nil && params.Network != "" {
		q["network"] = params.Network
	}
	return r.client.get(ctx, "/api/v1/crypto/cmc/dex/search", q)
}

// CoinMarketCap MCP endpoint for AI agents. Access 12 AI tools via MCP protocol. This is a POST endpoint; request body uses MCP JSON-RPC format. Available tools: get_crypto_quotes_latest (real-time quotes), search_cryptos (search coins), get_crypto_info (coin metadata/whitepapers), get_crypto_technical_analysis (SMA/EMA/MACD/RSI/Fibonacci), get_crypto_marketcap_technical_analysis (market cap TA), get_crypto_metrics (on-chain: holder distribution/address analysis), get_global_metrics_latest (global: total market cap/BTC dominance/Fear & Greed), get_global_crypto_derivatives_metrics (derivatives: leverage/ETF flows), trending_crypto_narratives (trending narratives with performance data), get_upcoming_macro_events (macro events affecting crypto), get_crypto_latest_news (latest crypto news), search_crypto_info (semantic search: whitepapers/concepts/docs). — $0.015/call
func (r *CoinmarketcapCmc) Mcp(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/cmc/mcp", body)
}

// CoinmarketcapResource provides access to all CoinMarketCap API endpoints.
type CoinmarketcapResource struct {
	client *Client
	Cmc *CoinmarketcapCmc
}

func newCoinmarketcapResource(c *Client) *CoinmarketcapResource {
	return &CoinmarketcapResource{
		client: c,
		Cmc: &CoinmarketcapCmc{client: c},
	}
}


