// Auto-generated by claw402 codegen — DO NOT EDIT
// Provider: DeepSeek (deepseek)

package claw402

import (
	"context"
	"encoding/json"
)

// DeepseekDeepseek provides methods for Deepseek deepseek endpoints.
type DeepseekDeepseek struct {
	client *Client
}

// Chat completions with DeepSeek-Chat (V3.2, general tasks) — $0.003/call
func (r *DeepseekDeepseek) Chat(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/ai/deepseek/chat", body)
}

// Chat completions with DeepSeek-Reasoner (chain-of-thought reasoning) — $0.005/call
func (r *DeepseekDeepseek) ChatReasoner(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/ai/deepseek/chat/reasoner", body)
}

// DeepSeek beta completions API (FIM / non-chat completions) — $0.003/call
func (r *DeepseekDeepseek) Completions(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/ai/deepseek/completions", body)
}

// List available DeepSeek models — $0.001/call
func (r *DeepseekDeepseek) Models(ctx context.Context) (json.RawMessage, error) {
	return r.client.get(ctx, "/api/v1/ai/deepseek/models", nil)
}

// DeepseekResource provides access to all DeepSeek API endpoints.
type DeepseekResource struct {
	client   *Client
	Deepseek *DeepseekDeepseek
}

func newDeepseekResource(c *Client) *DeepseekResource {
	return &DeepseekResource{
		client:   c,
		Deepseek: &DeepseekDeepseek{client: c},
	}
}
