// Auto-generated by claw402 codegen — DO NOT EDIT
// Provider: Gemini (Google) (gemini)

package claw402

import (
	"context"
	"encoding/json"
)

// GeminiGemini provides methods for Gemini gemini endpoints.
type GeminiGemini struct {
	client *Client
}

// Chat completions with Gemini 2.5 Pro (most powerful, 1M context) — $0.02/call
func (r *GeminiGemini) Chat25Pro(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/ai/gemini/chat/2.5-pro", body)
}

// Chat completions with Gemini 2.5 Flash (best value) — $0.003/call
func (r *GeminiGemini) Chat25Flash(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/ai/gemini/chat/2.5-flash", body)
}

// Chat completions with Gemini 2.5 Flash-Lite (fastest, cheapest) — $0.002/call
func (r *GeminiGemini) Chat25FlashLite(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/ai/gemini/chat/2.5-flash-lite", body)
}

// List available Gemini models — $0.001/call
func (r *GeminiGemini) Models(ctx context.Context) (json.RawMessage, error) {
	return r.client.get(ctx, "/api/v1/ai/gemini/models", nil)
}

// GeminiResource provides access to all Gemini (Google) API endpoints.
type GeminiResource struct {
	client *Client
	Gemini *GeminiGemini
}

func newGeminiResource(c *Client) *GeminiResource {
	return &GeminiResource{
		client: c,
		Gemini: &GeminiGemini{client: c},
	}
}


