// Auto-generated by claw402 codegen — DO NOT EDIT
// Provider: Grok (xAI) (grok)

package claw402

import (
	"context"
	"encoding/json"
)

// GrokGrok provides methods for Grok grok endpoints.
type GrokGrok struct {
	client *Client
}

// Chat completions with Grok-4 (flagship, 256K context) — $0.05/call
func (r *GrokGrok) Chat4(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/ai/grok/chat/4", body)
}

// Chat completions with Grok-3-mini (fast, great value) — $0.003/call
func (r *GrokGrok) Chat3Mini(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/ai/grok/chat/3-mini", body)
}

// List available Grok models — $0.001/call
func (r *GrokGrok) Models(ctx context.Context) (json.RawMessage, error) {
	return r.client.get(ctx, "/api/v1/ai/grok/models", nil)
}

// GrokResource provides access to all Grok (xAI) API endpoints.
type GrokResource struct {
	client *Client
	Grok *GrokGrok
}

func newGrokResource(c *Client) *GrokResource {
	return &GrokResource{
		client: c,
		Grok: &GrokGrok{client: c},
	}
}


