// Auto-generated by claw402 codegen — DO NOT EDIT
// Provider: Kimi (Moonshot AI) (kimi)

package claw402

import (
	"context"
	"encoding/json"
)

// KimiKimi provides methods for Kimi kimi endpoints.
type KimiKimi struct {
	client *Client
}

// Chat completions with Kimi K2 (1T MoE model, 256K context, excels at coding and reasoning) — $0.005/call
func (r *KimiKimi) ChatK2(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/ai/kimi/chat/k2", body)
}

// List available Kimi models — $0.001/call
func (r *KimiKimi) Models(ctx context.Context) (json.RawMessage, error) {
	return r.client.get(ctx, "/api/v1/ai/kimi/models", nil)
}

// KimiResource provides access to all Kimi (Moonshot AI) API endpoints.
type KimiResource struct {
	client *Client
	Kimi *KimiKimi
}

func newKimiResource(c *Client) *KimiResource {
	return &KimiResource{
		client: c,
		Kimi: &KimiKimi{client: c},
	}
}


