// Auto-generated by claw402 codegen — DO NOT EDIT
// Provider: nofxos.ai (nofxos)

package claw402

import (
	"context"
	"encoding/json"
)

// NofxosAi500 provides methods for Nofxos ai500 endpoints.
type NofxosAi500 struct {
	client *Client
}

// NofxosAi500ListParams are the query parameters for List.
type NofxosAi500ListParams struct {
	Limit string `json:"limit,omitempty"`
}

// AI500 high-potential coins list (AI Score > 70) — $0.001/call
func (r *NofxosAi500) List(ctx context.Context, params *NofxosAi500ListParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	return r.client.get(ctx, "/api/v1/nofx/ai500/list", q)
}

// AI500 index overall statistics — $0.001/call
func (r *NofxosAi500) Stats(ctx context.Context) (json.RawMessage, error) {
	return r.client.get(ctx, "/api/v1/nofx/ai500/stats", nil)
}

// NofxosAi300 provides methods for Nofxos ai300 endpoints.
type NofxosAi300 struct {
	client *Client
}

// NofxosAi300ListParams are the query parameters for List.
type NofxosAi300ListParams struct {
	Limit string `json:"limit,omitempty"`
}

// AI300 quant model rankings (by fund flow strength) — $0.001/call
func (r *NofxosAi300) List(ctx context.Context, params *NofxosAi300ListParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	return r.client.get(ctx, "/api/v1/nofx/ai300/list", q)
}

// AI300 model statistics (by signal strength distribution) — $0.001/call
func (r *NofxosAi300) Stats(ctx context.Context) (json.RawMessage, error) {
	return r.client.get(ctx, "/api/v1/nofx/ai300/stats", nil)
}

// NofxosOi provides methods for Nofxos oi endpoints.
type NofxosOi struct {
	client *Client
}

// NofxosOiTopRankingParams are the query parameters for TopRanking.
type NofxosOiTopRankingParams struct {
	Limit string `json:"limit,omitempty"`
	Duration string `json:"duration,omitempty"`
}

// Top open interest increase rankings — $0.001/call
func (r *NofxosOi) TopRanking(ctx context.Context, params *NofxosOiTopRankingParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	if params != nil && params.Duration != "" {
		q["duration"] = params.Duration
	}
	return r.client.get(ctx, "/api/v1/nofx/oi/top-ranking", q)
}

// NofxosOiLowRankingParams are the query parameters for LowRanking.
type NofxosOiLowRankingParams struct {
	Limit string `json:"limit,omitempty"`
	Duration string `json:"duration,omitempty"`
}

// Top open interest decrease rankings — $0.001/call
func (r *NofxosOi) LowRanking(ctx context.Context, params *NofxosOiLowRankingParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	if params != nil && params.Duration != "" {
		q["duration"] = params.Duration
	}
	return r.client.get(ctx, "/api/v1/nofx/oi/low-ranking", q)
}

// NofxosNetflow provides methods for Nofxos netflow endpoints.
type NofxosNetflow struct {
	client *Client
}

// NofxosNetflowTopRankingParams are the query parameters for TopRanking.
type NofxosNetflowTopRankingParams struct {
	Limit string `json:"limit,omitempty"`
	Duration string `json:"duration,omitempty"`
	Type string `json:"type,omitempty"`
	Trade string `json:"trade,omitempty"`
}

// Top net capital inflow rankings — $0.001/call
func (r *NofxosNetflow) TopRanking(ctx context.Context, params *NofxosNetflowTopRankingParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	if params != nil && params.Duration != "" {
		q["duration"] = params.Duration
	}
	if params != nil && params.Type != "" {
		q["type"] = params.Type
	}
	if params != nil && params.Trade != "" {
		q["trade"] = params.Trade
	}
	return r.client.get(ctx, "/api/v1/nofx/netflow/top-ranking", q)
}

// NofxosNetflowLowRankingParams are the query parameters for LowRanking.
type NofxosNetflowLowRankingParams struct {
	Limit string `json:"limit,omitempty"`
	Duration string `json:"duration,omitempty"`
	Type string `json:"type,omitempty"`
	Trade string `json:"trade,omitempty"`
}

// Top net capital outflow rankings — $0.001/call
func (r *NofxosNetflow) LowRanking(ctx context.Context, params *NofxosNetflowLowRankingParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	if params != nil && params.Duration != "" {
		q["duration"] = params.Duration
	}
	if params != nil && params.Type != "" {
		q["type"] = params.Type
	}
	if params != nil && params.Trade != "" {
		q["trade"] = params.Trade
	}
	return r.client.get(ctx, "/api/v1/nofx/netflow/low-ranking", q)
}

// NofxosPrice provides methods for Nofxos price endpoints.
type NofxosPrice struct {
	client *Client
}

// NofxosPriceRankingParams are the query parameters for Ranking.
type NofxosPriceRankingParams struct {
	Duration string `json:"duration,omitempty"`
}

// Price change rankings (gainers & losers) — $0.001/call
func (r *NofxosPrice) Ranking(ctx context.Context, params *NofxosPriceRankingParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Duration != "" {
		q["duration"] = params.Duration
	}
	return r.client.get(ctx, "/api/v1/nofx/price/ranking", q)
}

// NofxosLongShort provides methods for Nofxos longShort endpoints.
type NofxosLongShort struct {
	client *Client
}

// NofxosLongShortListParams are the query parameters for List.
type NofxosLongShortListParams struct {
	Limit string `json:"limit,omitempty"`
}

// Long/short ratio anomaly coin list — $0.001/call
func (r *NofxosLongShort) List(ctx context.Context, params *NofxosLongShortListParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	return r.client.get(ctx, "/api/v1/nofx/long-short/list", q)
}

// NofxosFundingRate provides methods for Nofxos fundingRate endpoints.
type NofxosFundingRate struct {
	client *Client
}

// NofxosFundingRateTopParams are the query parameters for Top.
type NofxosFundingRateTopParams struct {
	Limit string `json:"limit,omitempty"`
}

// Top positive funding rate rankings — $0.001/call
func (r *NofxosFundingRate) Top(ctx context.Context, params *NofxosFundingRateTopParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	return r.client.get(ctx, "/api/v1/nofx/funding-rate/top", q)
}

// NofxosFundingRateLowParams are the query parameters for Low.
type NofxosFundingRateLowParams struct {
	Limit string `json:"limit,omitempty"`
}

// Top negative funding rate rankings — $0.001/call
func (r *NofxosFundingRate) Low(ctx context.Context, params *NofxosFundingRateLowParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	return r.client.get(ctx, "/api/v1/nofx/funding-rate/low", q)
}

// NofxosOiCap provides methods for Nofxos oiCap endpoints.
type NofxosOiCap struct {
	client *Client
}

// NofxosOiCapRankingParams are the query parameters for Ranking.
type NofxosOiCapRankingParams struct {
	Limit string `json:"limit,omitempty"`
}

// Open interest market cap rankings — $0.001/call
func (r *NofxosOiCap) Ranking(ctx context.Context, params *NofxosOiCapRankingParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	return r.client.get(ctx, "/api/v1/nofx/oi-cap/ranking", q)
}

// NofxosUpbit provides methods for Nofxos upbit endpoints.
type NofxosUpbit struct {
	client *Client
}

// NofxosUpbitHotParams are the query parameters for Hot.
type NofxosUpbitHotParams struct {
	Limit string `json:"limit,omitempty"`
}

// Upbit hot coins rankings (by trading volume) — $0.001/call
func (r *NofxosUpbit) Hot(ctx context.Context, params *NofxosUpbitHotParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	return r.client.get(ctx, "/api/v1/nofx/upbit/hot", q)
}

// NofxosUpbitNetflowTopRankingParams are the query parameters for NetflowTopRanking.
type NofxosUpbitNetflowTopRankingParams struct {
	Limit string `json:"limit,omitempty"`
	Duration string `json:"duration,omitempty"`
}

// Upbit net inflow rankings — $0.001/call
func (r *NofxosUpbit) NetflowTopRanking(ctx context.Context, params *NofxosUpbitNetflowTopRankingParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	if params != nil && params.Duration != "" {
		q["duration"] = params.Duration
	}
	return r.client.get(ctx, "/api/v1/nofx/upbit/netflow/top-ranking", q)
}

// NofxosUpbitNetflowLowRankingParams are the query parameters for NetflowLowRanking.
type NofxosUpbitNetflowLowRankingParams struct {
	Limit string `json:"limit,omitempty"`
	Duration string `json:"duration,omitempty"`
}

// Upbit net outflow rankings — $0.001/call
func (r *NofxosUpbit) NetflowLowRanking(ctx context.Context, params *NofxosUpbitNetflowLowRankingParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	if params != nil && params.Duration != "" {
		q["duration"] = params.Duration
	}
	return r.client.get(ctx, "/api/v1/nofx/upbit/netflow/low-ranking", q)
}

// NofxosHeatmap provides methods for Nofxos heatmap endpoints.
type NofxosHeatmap struct {
	client *Client
}

// NofxosHeatmapListParams are the query parameters for List.
type NofxosHeatmapListParams struct {
	Trade string `json:"trade,omitempty"`
	Limit string `json:"limit,omitempty"`
}

// Order book heatmap overview (all coins) — $0.001/call
func (r *NofxosHeatmap) List(ctx context.Context, params *NofxosHeatmapListParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Trade != "" {
		q["trade"] = params.Trade
	}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	return r.client.get(ctx, "/api/v1/nofx/heatmap/list", q)
}

// NofxosQueryRank provides methods for Nofxos queryRank endpoints.
type NofxosQueryRank struct {
	client *Client
}

// NofxosQueryRankListParams are the query parameters for List.
type NofxosQueryRankListParams struct {
	Limit string `json:"limit,omitempty"`
}

// Today's most searched coin rankings — $0.001/call
func (r *NofxosQueryRank) List(ctx context.Context, params *NofxosQueryRankListParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	return r.client.get(ctx, "/api/v1/nofx/query-rank/list", q)
}

// NofxosResource provides access to all nofxos.ai API endpoints.
type NofxosResource struct {
	client *Client
	Ai500 *NofxosAi500
	Ai300 *NofxosAi300
	Oi *NofxosOi
	Netflow *NofxosNetflow
	Price *NofxosPrice
	LongShort *NofxosLongShort
	FundingRate *NofxosFundingRate
	OiCap *NofxosOiCap
	Upbit *NofxosUpbit
	Heatmap *NofxosHeatmap
	QueryRank *NofxosQueryRank
}

func newNofxosResource(c *Client) *NofxosResource {
	return &NofxosResource{
		client: c,
		Ai500: &NofxosAi500{client: c},
		Ai300: &NofxosAi300{client: c},
		Oi: &NofxosOi{client: c},
		Netflow: &NofxosNetflow{client: c},
		Price: &NofxosPrice{client: c},
		LongShort: &NofxosLongShort{client: c},
		FundingRate: &NofxosFundingRate{client: c},
		OiCap: &NofxosOiCap{client: c},
		Upbit: &NofxosUpbit{client: c},
		Heatmap: &NofxosHeatmap{client: c},
		QueryRank: &NofxosQueryRank{client: c},
	}
}


