// Auto-generated by claw402 codegen — DO NOT EDIT
// Provider: OpenAI (openai)

package claw402

import (
	"context"
	"encoding/json"
)

// OpenaiOpenai provides methods for Openai openai endpoints.
type OpenaiOpenai struct {
	client *Client
}

// Chat completions with GPT-4o (default) — $0.01/call
func (r *OpenaiOpenai) Chat(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/ai/openai/chat", body)
}

// Chat completions with GPT-4o-mini (faster, cheaper) — $0.003/call
func (r *OpenaiOpenai) ChatMini(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/ai/openai/chat/mini", body)
}

// Text embeddings with text-embedding-3-small — $0.002/call
func (r *OpenaiOpenai) Embeddings(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/ai/openai/embeddings", body)
}

// Text embeddings with text-embedding-3-large — $0.005/call
func (r *OpenaiOpenai) EmbeddingsLarge(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/ai/openai/embeddings/large", body)
}

// Image generation with DALL·E — $0.05/call
func (r *OpenaiOpenai) Images(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/ai/openai/images", body)
}

// List available models — $0.001/call
func (r *OpenaiOpenai) Models(ctx context.Context) (json.RawMessage, error) {
	return r.client.get(ctx, "/api/v1/ai/openai/models", nil)
}

// OpenaiResource provides access to all OpenAI API endpoints.
type OpenaiResource struct {
	client *Client
	Openai *OpenaiOpenai
}

func newOpenaiResource(c *Client) *OpenaiResource {
	return &OpenaiResource{
		client: c,
		Openai: &OpenaiOpenai{client: c},
	}
}


