// Auto-generated by claw402 codegen — DO NOT EDIT
// Provider: Polygon.io (polygon)

package claw402

import (
	"context"
	"encoding/json"
)

// PolygonAggs provides methods for Polygon aggs endpoints.
type PolygonAggs struct {
	client *Client
}

// PolygonAggsTickerParams are the query parameters for Ticker.
type PolygonAggsTickerParams struct {
	StocksTicker string `json:"stocksTicker,omitempty"`
	Multiplier string `json:"multiplier,omitempty"`
	Timespan string `json:"timespan,omitempty"`
	From string `json:"from,omitempty"`
	To string `json:"to,omitempty"`
	Adjusted string `json:"adjusted,omitempty"`
	Sort string `json:"sort,omitempty"`
	Limit string `json:"limit,omitempty"`
}

// Get aggregate bars (OHLCV) for any stock ticker — $0.001/call
func (r *PolygonAggs) Ticker(ctx context.Context, params *PolygonAggsTickerParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.StocksTicker != "" {
		q["stocksTicker"] = params.StocksTicker
	}
	if params != nil && params.Multiplier != "" {
		q["multiplier"] = params.Multiplier
	}
	if params != nil && params.Timespan != "" {
		q["timespan"] = params.Timespan
	}
	if params != nil && params.From != "" {
		q["from"] = params.From
	}
	if params != nil && params.To != "" {
		q["to"] = params.To
	}
	if params != nil && params.Adjusted != "" {
		q["adjusted"] = params.Adjusted
	}
	if params != nil && params.Sort != "" {
		q["sort"] = params.Sort
	}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	return r.client.get(ctx, "/api/v1/polygon/aggs/ticker", q)
}

// PolygonAggsGroupedParams are the query parameters for Grouped.
type PolygonAggsGroupedParams struct {
	Date string `json:"date,omitempty"`
	Adjusted string `json:"adjusted,omitempty"`
	IncludeOtc string `json:"include_otc,omitempty"`
}

// Get aggregate bars for entire US market on a specific date — $0.005/call
func (r *PolygonAggs) Grouped(ctx context.Context, params *PolygonAggsGroupedParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Date != "" {
		q["date"] = params.Date
	}
	if params != nil && params.Adjusted != "" {
		q["adjusted"] = params.Adjusted
	}
	if params != nil && params.IncludeOtc != "" {
		q["include_otc"] = params.IncludeOtc
	}
	return r.client.get(ctx, "/api/v1/polygon/aggs/grouped", q)
}

// PolygonSnapshot provides methods for Polygon snapshot endpoints.
type PolygonSnapshot struct {
	client *Client
}

// PolygonSnapshotTickerParams are the query parameters for Ticker.
type PolygonSnapshotTickerParams struct {
	StocksTicker string `json:"stocksTicker,omitempty"`
}

// Get real-time snapshot for any ticker — $0.001/call
func (r *PolygonSnapshot) Ticker(ctx context.Context, params *PolygonSnapshotTickerParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.StocksTicker != "" {
		q["stocksTicker"] = params.StocksTicker
	}
	return r.client.get(ctx, "/api/v1/polygon/snapshot/ticker", q)
}

// PolygonSnapshotAllParams are the query parameters for All.
type PolygonSnapshotAllParams struct {
	Tickers string `json:"tickers,omitempty"`
	IncludeOtc string `json:"include_otc,omitempty"`
}

// Get snapshots for all US stock tickers — $0.005/call
func (r *PolygonSnapshot) All(ctx context.Context, params *PolygonSnapshotAllParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Tickers != "" {
		q["tickers"] = params.Tickers
	}
	if params != nil && params.IncludeOtc != "" {
		q["include_otc"] = params.IncludeOtc
	}
	return r.client.get(ctx, "/api/v1/polygon/snapshot/all", q)
}

// PolygonSnapshotGainersParams are the query parameters for Gainers.
type PolygonSnapshotGainersParams struct {
	IncludeOtc string `json:"include_otc,omitempty"`
}

// Get top 20 gainers of the day — $0.001/call
func (r *PolygonSnapshot) Gainers(ctx context.Context, params *PolygonSnapshotGainersParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.IncludeOtc != "" {
		q["include_otc"] = params.IncludeOtc
	}
	return r.client.get(ctx, "/api/v1/polygon/snapshot/gainers", q)
}

// PolygonSnapshotLosersParams are the query parameters for Losers.
type PolygonSnapshotLosersParams struct {
	IncludeOtc string `json:"include_otc,omitempty"`
}

// Get top 20 losers of the day — $0.001/call
func (r *PolygonSnapshot) Losers(ctx context.Context, params *PolygonSnapshotLosersParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.IncludeOtc != "" {
		q["include_otc"] = params.IncludeOtc
	}
	return r.client.get(ctx, "/api/v1/polygon/snapshot/losers", q)
}

// PolygonOptions provides methods for Polygon options endpoints.
type PolygonOptions struct {
	client *Client
}

// PolygonOptionsContractsParams are the query parameters for Contracts.
type PolygonOptionsContractsParams struct {
	UnderlyingTicker string `json:"underlying_ticker,omitempty"`
	ContractType string `json:"contract_type,omitempty"`
	ExpirationDate string `json:"expiration_date,omitempty"`
	ExpirationDateGte string `json:"expiration_date.gte,omitempty"`
	ExpirationDateGt string `json:"expiration_date.gt,omitempty"`
	ExpirationDateLte string `json:"expiration_date.lte,omitempty"`
	ExpirationDateLt string `json:"expiration_date.lt,omitempty"`
	AsOf string `json:"as_of,omitempty"`
	StrikePrice string `json:"strike_price,omitempty"`
	StrikePriceGte string `json:"strike_price.gte,omitempty"`
	StrikePriceGt string `json:"strike_price.gt,omitempty"`
	StrikePriceLte string `json:"strike_price.lte,omitempty"`
	StrikePriceLt string `json:"strike_price.lt,omitempty"`
	Expired string `json:"expired,omitempty"`
	Order string `json:"order,omitempty"`
	Limit string `json:"limit,omitempty"`
	Sort string `json:"sort,omitempty"`
}

// Query for historical options contracts — $0.002/call
func (r *PolygonOptions) Contracts(ctx context.Context, params *PolygonOptionsContractsParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.UnderlyingTicker != "" {
		q["underlying_ticker"] = params.UnderlyingTicker
	}
	if params != nil && params.ContractType != "" {
		q["contract_type"] = params.ContractType
	}
	if params != nil && params.ExpirationDate != "" {
		q["expiration_date"] = params.ExpirationDate
	}
	if params != nil && params.ExpirationDateGte != "" {
		q["expiration_date.gte"] = params.ExpirationDateGte
	}
	if params != nil && params.ExpirationDateGt != "" {
		q["expiration_date.gt"] = params.ExpirationDateGt
	}
	if params != nil && params.ExpirationDateLte != "" {
		q["expiration_date.lte"] = params.ExpirationDateLte
	}
	if params != nil && params.ExpirationDateLt != "" {
		q["expiration_date.lt"] = params.ExpirationDateLt
	}
	if params != nil && params.AsOf != "" {
		q["as_of"] = params.AsOf
	}
	if params != nil && params.StrikePrice != "" {
		q["strike_price"] = params.StrikePrice
	}
	if params != nil && params.StrikePriceGte != "" {
		q["strike_price.gte"] = params.StrikePriceGte
	}
	if params != nil && params.StrikePriceGt != "" {
		q["strike_price.gt"] = params.StrikePriceGt
	}
	if params != nil && params.StrikePriceLte != "" {
		q["strike_price.lte"] = params.StrikePriceLte
	}
	if params != nil && params.StrikePriceLt != "" {
		q["strike_price.lt"] = params.StrikePriceLt
	}
	if params != nil && params.Expired != "" {
		q["expired"] = params.Expired
	}
	if params != nil && params.Order != "" {
		q["order"] = params.Order
	}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	if params != nil && params.Sort != "" {
		q["sort"] = params.Sort
	}
	return r.client.get(ctx, "/api/v1/polygon/options/contracts", q)
}

// PolygonOptionsContractDetailsParams are the query parameters for ContractDetails.
type PolygonOptionsContractDetailsParams struct {
	OptionsTicker string `json:"options_ticker,omitempty"`
	AsOf string `json:"as_of,omitempty"`
}

// Get details for a single options contract — $0.001/call
func (r *PolygonOptions) ContractDetails(ctx context.Context, params *PolygonOptionsContractDetailsParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.OptionsTicker != "" {
		q["options_ticker"] = params.OptionsTicker
	}
	if params != nil && params.AsOf != "" {
		q["as_of"] = params.AsOf
	}
	return r.client.get(ctx, "/api/v1/polygon/options/contract-details", q)
}

// PolygonOptionsSnapshotParams are the query parameters for Snapshot.
type PolygonOptionsSnapshotParams struct {
	UnderlyingAsset string `json:"underlyingAsset,omitempty"`
	StrikePrice string `json:"strike_price,omitempty"`
	StrikePriceGte string `json:"strike_price.gte,omitempty"`
	StrikePriceGt string `json:"strike_price.gt,omitempty"`
	StrikePriceLte string `json:"strike_price.lte,omitempty"`
	StrikePriceLt string `json:"strike_price.lt,omitempty"`
	ExpirationDate string `json:"expiration_date,omitempty"`
	ExpirationDateGte string `json:"expiration_date.gte,omitempty"`
	ExpirationDateGt string `json:"expiration_date.gt,omitempty"`
	ExpirationDateLte string `json:"expiration_date.lte,omitempty"`
	ExpirationDateLt string `json:"expiration_date.lt,omitempty"`
	ContractType string `json:"contract_type,omitempty"`
	Order string `json:"order,omitempty"`
	Limit string `json:"limit,omitempty"`
}

// Get snapshot of options chain for an underlying asset — $0.002/call
func (r *PolygonOptions) Snapshot(ctx context.Context, params *PolygonOptionsSnapshotParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.UnderlyingAsset != "" {
		q["underlyingAsset"] = params.UnderlyingAsset
	}
	if params != nil && params.StrikePrice != "" {
		q["strike_price"] = params.StrikePrice
	}
	if params != nil && params.StrikePriceGte != "" {
		q["strike_price.gte"] = params.StrikePriceGte
	}
	if params != nil && params.StrikePriceGt != "" {
		q["strike_price.gt"] = params.StrikePriceGt
	}
	if params != nil && params.StrikePriceLte != "" {
		q["strike_price.lte"] = params.StrikePriceLte
	}
	if params != nil && params.StrikePriceLt != "" {
		q["strike_price.lt"] = params.StrikePriceLt
	}
	if params != nil && params.ExpirationDate != "" {
		q["expiration_date"] = params.ExpirationDate
	}
	if params != nil && params.ExpirationDateGte != "" {
		q["expiration_date.gte"] = params.ExpirationDateGte
	}
	if params != nil && params.ExpirationDateGt != "" {
		q["expiration_date.gt"] = params.ExpirationDateGt
	}
	if params != nil && params.ExpirationDateLte != "" {
		q["expiration_date.lte"] = params.ExpirationDateLte
	}
	if params != nil && params.ExpirationDateLt != "" {
		q["expiration_date.lt"] = params.ExpirationDateLt
	}
	if params != nil && params.ContractType != "" {
		q["contract_type"] = params.ContractType
	}
	if params != nil && params.Order != "" {
		q["order"] = params.Order
	}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	return r.client.get(ctx, "/api/v1/polygon/options/snapshot", q)
}

// PolygonOptionsSnapshotContractParams are the query parameters for SnapshotContract.
type PolygonOptionsSnapshotContractParams struct {
	UnderlyingAsset string `json:"underlyingAsset,omitempty"`
	OptionContract string `json:"optionContract,omitempty"`
}

// Get snapshot of a single options contract — $0.001/call
func (r *PolygonOptions) SnapshotContract(ctx context.Context, params *PolygonOptionsSnapshotContractParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.UnderlyingAsset != "" {
		q["underlyingAsset"] = params.UnderlyingAsset
	}
	if params != nil && params.OptionContract != "" {
		q["optionContract"] = params.OptionContract
	}
	return r.client.get(ctx, "/api/v1/polygon/options/snapshot/contract", q)
}

// PolygonResource provides access to all Polygon.io API endpoints.
type PolygonResource struct {
	client *Client
	Aggs *PolygonAggs
	Snapshot *PolygonSnapshot
	Options *PolygonOptions
}

func newPolygonResource(c *Client) *PolygonResource {
	return &PolygonResource{
		client: c,
		Aggs: &PolygonAggs{client: c},
		Snapshot: &PolygonSnapshot{client: c},
		Options: &PolygonOptions{client: c},
	}
}

// PolygonPrevCloseParams are the query parameters for PrevClose.
type PolygonPrevCloseParams struct {
	StocksTicker string `json:"stocksTicker,omitempty"`
	Adjusted string `json:"adjusted,omitempty"`
}

// Get previous day close for any ticker — $0.001/call
func (r *PolygonResource) PrevClose(ctx context.Context, params *PolygonPrevCloseParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.StocksTicker != "" {
		q["stocksTicker"] = params.StocksTicker
	}
	if params != nil && params.Adjusted != "" {
		q["adjusted"] = params.Adjusted
	}
	return r.client.get(ctx, "/api/v1/polygon/prev-close", q)
}

// PolygonTradesParams are the query parameters for Trades.
type PolygonTradesParams struct {
	StockTicker string `json:"stockTicker,omitempty"`
	TimestampGte string `json:"timestamp.gte,omitempty"`
	TimestampLte string `json:"timestamp.lte,omitempty"`
	TimestampGt string `json:"timestamp.gt,omitempty"`
	TimestampLt string `json:"timestamp.lt,omitempty"`
	Order string `json:"order,omitempty"`
	Limit string `json:"limit,omitempty"`
	Sort string `json:"sort,omitempty"`
}

// Get tick-by-tick trade data for any stock — $0.005/call
func (r *PolygonResource) Trades(ctx context.Context, params *PolygonTradesParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.StockTicker != "" {
		q["stockTicker"] = params.StockTicker
	}
	if params != nil && params.TimestampGte != "" {
		q["timestamp.gte"] = params.TimestampGte
	}
	if params != nil && params.TimestampLte != "" {
		q["timestamp.lte"] = params.TimestampLte
	}
	if params != nil && params.TimestampGt != "" {
		q["timestamp.gt"] = params.TimestampGt
	}
	if params != nil && params.TimestampLt != "" {
		q["timestamp.lt"] = params.TimestampLt
	}
	if params != nil && params.Order != "" {
		q["order"] = params.Order
	}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	if params != nil && params.Sort != "" {
		q["sort"] = params.Sort
	}
	return r.client.get(ctx, "/api/v1/polygon/trades", q)
}

// PolygonLastTradeParams are the query parameters for LastTrade.
type PolygonLastTradeParams struct {
	StocksTicker string `json:"stocksTicker,omitempty"`
}

// Get most recent trade for a ticker — $0.001/call
func (r *PolygonResource) LastTrade(ctx context.Context, params *PolygonLastTradeParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.StocksTicker != "" {
		q["stocksTicker"] = params.StocksTicker
	}
	return r.client.get(ctx, "/api/v1/polygon/last-trade", q)
}

// PolygonQuotesParams are the query parameters for Quotes.
type PolygonQuotesParams struct {
	StockTicker string `json:"stockTicker,omitempty"`
	TimestampGte string `json:"timestamp.gte,omitempty"`
	TimestampLte string `json:"timestamp.lte,omitempty"`
	TimestampGt string `json:"timestamp.gt,omitempty"`
	TimestampLt string `json:"timestamp.lt,omitempty"`
	Order string `json:"order,omitempty"`
	Limit string `json:"limit,omitempty"`
	Sort string `json:"sort,omitempty"`
}

// Get NBBO quotes for any stock — $0.005/call
func (r *PolygonResource) Quotes(ctx context.Context, params *PolygonQuotesParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.StockTicker != "" {
		q["stockTicker"] = params.StockTicker
	}
	if params != nil && params.TimestampGte != "" {
		q["timestamp.gte"] = params.TimestampGte
	}
	if params != nil && params.TimestampLte != "" {
		q["timestamp.lte"] = params.TimestampLte
	}
	if params != nil && params.TimestampGt != "" {
		q["timestamp.gt"] = params.TimestampGt
	}
	if params != nil && params.TimestampLt != "" {
		q["timestamp.lt"] = params.TimestampLt
	}
	if params != nil && params.Order != "" {
		q["order"] = params.Order
	}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	if params != nil && params.Sort != "" {
		q["sort"] = params.Sort
	}
	return r.client.get(ctx, "/api/v1/polygon/quotes", q)
}

// PolygonLastQuoteParams are the query parameters for LastQuote.
type PolygonLastQuoteParams struct {
	StocksTicker string `json:"stocksTicker,omitempty"`
}

// Get most recent NBBO quote for a ticker — $0.001/call
func (r *PolygonResource) LastQuote(ctx context.Context, params *PolygonLastQuoteParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.StocksTicker != "" {
		q["stocksTicker"] = params.StocksTicker
	}
	return r.client.get(ctx, "/api/v1/polygon/last-quote", q)
}

// PolygonTickersParams are the query parameters for Tickers.
type PolygonTickersParams struct {
	Ticker string `json:"ticker,omitempty"`
	Type string `json:"type,omitempty"`
	Market string `json:"market,omitempty"`
	Exchange string `json:"exchange,omitempty"`
	Cusip string `json:"cusip,omitempty"`
	Cik string `json:"cik,omitempty"`
	Date string `json:"date,omitempty"`
	Search string `json:"search,omitempty"`
	Active string `json:"active,omitempty"`
	Order string `json:"order,omitempty"`
	Limit string `json:"limit,omitempty"`
	Sort string `json:"sort,omitempty"`
}

// Query all ticker symbols with optional filters — $0.001/call
func (r *PolygonResource) Tickers(ctx context.Context, params *PolygonTickersParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Ticker != "" {
		q["ticker"] = params.Ticker
	}
	if params != nil && params.Type != "" {
		q["type"] = params.Type
	}
	if params != nil && params.Market != "" {
		q["market"] = params.Market
	}
	if params != nil && params.Exchange != "" {
		q["exchange"] = params.Exchange
	}
	if params != nil && params.Cusip != "" {
		q["cusip"] = params.Cusip
	}
	if params != nil && params.Cik != "" {
		q["cik"] = params.Cik
	}
	if params != nil && params.Date != "" {
		q["date"] = params.Date
	}
	if params != nil && params.Search != "" {
		q["search"] = params.Search
	}
	if params != nil && params.Active != "" {
		q["active"] = params.Active
	}
	if params != nil && params.Order != "" {
		q["order"] = params.Order
	}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	if params != nil && params.Sort != "" {
		q["sort"] = params.Sort
	}
	return r.client.get(ctx, "/api/v1/polygon/tickers", q)
}

// PolygonTickerDetailsParams are the query parameters for TickerDetails.
type PolygonTickerDetailsParams struct {
	Ticker string `json:"ticker,omitempty"`
	Date string `json:"date,omitempty"`
}

// Get detailed information about any ticker — $0.001/call
func (r *PolygonResource) TickerDetails(ctx context.Context, params *PolygonTickerDetailsParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Ticker != "" {
		q["ticker"] = params.Ticker
	}
	if params != nil && params.Date != "" {
		q["date"] = params.Date
	}
	return r.client.get(ctx, "/api/v1/polygon/ticker-details", q)
}

// PolygonTickerNewsParams are the query parameters for TickerNews.
type PolygonTickerNewsParams struct {
	Ticker string `json:"ticker,omitempty"`
	PublishedUtc string `json:"published_utc,omitempty"`
	PublishedUtcGte string `json:"published_utc.gte,omitempty"`
	PublishedUtcLte string `json:"published_utc.lte,omitempty"`
	Order string `json:"order,omitempty"`
	Limit string `json:"limit,omitempty"`
	Sort string `json:"sort,omitempty"`
}

// Get news articles for tickers — $0.001/call
func (r *PolygonResource) TickerNews(ctx context.Context, params *PolygonTickerNewsParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Ticker != "" {
		q["ticker"] = params.Ticker
	}
	if params != nil && params.PublishedUtc != "" {
		q["published_utc"] = params.PublishedUtc
	}
	if params != nil && params.PublishedUtcGte != "" {
		q["published_utc.gte"] = params.PublishedUtcGte
	}
	if params != nil && params.PublishedUtcLte != "" {
		q["published_utc.lte"] = params.PublishedUtcLte
	}
	if params != nil && params.Order != "" {
		q["order"] = params.Order
	}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	if params != nil && params.Sort != "" {
		q["sort"] = params.Sort
	}
	return r.client.get(ctx, "/api/v1/polygon/ticker-news", q)
}

// Get upcoming US market holidays and early closes — $0.001/call
func (r *PolygonResource) MarketHolidays(ctx context.Context) (json.RawMessage, error) {
	return r.client.get(ctx, "/api/v1/polygon/market-holidays", nil)
}

// Get current US market trading status — $0.001/call
func (r *PolygonResource) MarketStatus(ctx context.Context) (json.RawMessage, error) {
	return r.client.get(ctx, "/api/v1/polygon/market-status", nil)
}

// PolygonExchangesParams are the query parameters for Exchanges.
type PolygonExchangesParams struct {
	AssetClass string `json:"asset_class,omitempty"`
	Locale string `json:"locale,omitempty"`
}

// List all stock exchanges — $0.001/call
func (r *PolygonResource) Exchanges(ctx context.Context, params *PolygonExchangesParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.AssetClass != "" {
		q["asset_class"] = params.AssetClass
	}
	if params != nil && params.Locale != "" {
		q["locale"] = params.Locale
	}
	return r.client.get(ctx, "/api/v1/polygon/exchanges", q)
}

// PolygonSmaParams are the query parameters for Sma.
type PolygonSmaParams struct {
	StockTicker string `json:"stockTicker,omitempty"`
	Timestamp string `json:"timestamp,omitempty"`
	Timespan string `json:"timespan,omitempty"`
	Adjusted string `json:"adjusted,omitempty"`
	Window string `json:"window,omitempty"`
	SeriesType string `json:"series_type,omitempty"`
	ExpandUnderlying string `json:"expand_underlying,omitempty"`
	Order string `json:"order,omitempty"`
	Limit string `json:"limit,omitempty"`
}

// Get Simple Moving Average (SMA) for any stock — $0.001/call
func (r *PolygonResource) Sma(ctx context.Context, params *PolygonSmaParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.StockTicker != "" {
		q["stockTicker"] = params.StockTicker
	}
	if params != nil && params.Timestamp != "" {
		q["timestamp"] = params.Timestamp
	}
	if params != nil && params.Timespan != "" {
		q["timespan"] = params.Timespan
	}
	if params != nil && params.Adjusted != "" {
		q["adjusted"] = params.Adjusted
	}
	if params != nil && params.Window != "" {
		q["window"] = params.Window
	}
	if params != nil && params.SeriesType != "" {
		q["series_type"] = params.SeriesType
	}
	if params != nil && params.ExpandUnderlying != "" {
		q["expand_underlying"] = params.ExpandUnderlying
	}
	if params != nil && params.Order != "" {
		q["order"] = params.Order
	}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	return r.client.get(ctx, "/api/v1/polygon/sma", q)
}

// PolygonEmaParams are the query parameters for Ema.
type PolygonEmaParams struct {
	StockTicker string `json:"stockTicker,omitempty"`
	Timestamp string `json:"timestamp,omitempty"`
	Timespan string `json:"timespan,omitempty"`
	Adjusted string `json:"adjusted,omitempty"`
	Window string `json:"window,omitempty"`
	SeriesType string `json:"series_type,omitempty"`
	ExpandUnderlying string `json:"expand_underlying,omitempty"`
	Order string `json:"order,omitempty"`
	Limit string `json:"limit,omitempty"`
}

// Get Exponential Moving Average (EMA) for any stock — $0.001/call
func (r *PolygonResource) Ema(ctx context.Context, params *PolygonEmaParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.StockTicker != "" {
		q["stockTicker"] = params.StockTicker
	}
	if params != nil && params.Timestamp != "" {
		q["timestamp"] = params.Timestamp
	}
	if params != nil && params.Timespan != "" {
		q["timespan"] = params.Timespan
	}
	if params != nil && params.Adjusted != "" {
		q["adjusted"] = params.Adjusted
	}
	if params != nil && params.Window != "" {
		q["window"] = params.Window
	}
	if params != nil && params.SeriesType != "" {
		q["series_type"] = params.SeriesType
	}
	if params != nil && params.ExpandUnderlying != "" {
		q["expand_underlying"] = params.ExpandUnderlying
	}
	if params != nil && params.Order != "" {
		q["order"] = params.Order
	}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	return r.client.get(ctx, "/api/v1/polygon/ema", q)
}

// PolygonMacdParams are the query parameters for Macd.
type PolygonMacdParams struct {
	StockTicker string `json:"stockTicker,omitempty"`
	Timestamp string `json:"timestamp,omitempty"`
	Timespan string `json:"timespan,omitempty"`
	Adjusted string `json:"adjusted,omitempty"`
	ShortWindow string `json:"short_window,omitempty"`
	LongWindow string `json:"long_window,omitempty"`
	SignalWindow string `json:"signal_window,omitempty"`
	SeriesType string `json:"series_type,omitempty"`
	ExpandUnderlying string `json:"expand_underlying,omitempty"`
	Order string `json:"order,omitempty"`
	Limit string `json:"limit,omitempty"`
}

// Get Moving Average Convergence/Divergence (MACD) — $0.001/call
func (r *PolygonResource) Macd(ctx context.Context, params *PolygonMacdParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.StockTicker != "" {
		q["stockTicker"] = params.StockTicker
	}
	if params != nil && params.Timestamp != "" {
		q["timestamp"] = params.Timestamp
	}
	if params != nil && params.Timespan != "" {
		q["timespan"] = params.Timespan
	}
	if params != nil && params.Adjusted != "" {
		q["adjusted"] = params.Adjusted
	}
	if params != nil && params.ShortWindow != "" {
		q["short_window"] = params.ShortWindow
	}
	if params != nil && params.LongWindow != "" {
		q["long_window"] = params.LongWindow
	}
	if params != nil && params.SignalWindow != "" {
		q["signal_window"] = params.SignalWindow
	}
	if params != nil && params.SeriesType != "" {
		q["series_type"] = params.SeriesType
	}
	if params != nil && params.ExpandUnderlying != "" {
		q["expand_underlying"] = params.ExpandUnderlying
	}
	if params != nil && params.Order != "" {
		q["order"] = params.Order
	}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	return r.client.get(ctx, "/api/v1/polygon/macd", q)
}

// PolygonRsiParams are the query parameters for Rsi.
type PolygonRsiParams struct {
	StockTicker string `json:"stockTicker,omitempty"`
	Timestamp string `json:"timestamp,omitempty"`
	Timespan string `json:"timespan,omitempty"`
	Adjusted string `json:"adjusted,omitempty"`
	Window string `json:"window,omitempty"`
	SeriesType string `json:"series_type,omitempty"`
	ExpandUnderlying string `json:"expand_underlying,omitempty"`
	Order string `json:"order,omitempty"`
	Limit string `json:"limit,omitempty"`
}

// Get Relative Strength Index (RSI) — $0.001/call
func (r *PolygonResource) Rsi(ctx context.Context, params *PolygonRsiParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.StockTicker != "" {
		q["stockTicker"] = params.StockTicker
	}
	if params != nil && params.Timestamp != "" {
		q["timestamp"] = params.Timestamp
	}
	if params != nil && params.Timespan != "" {
		q["timespan"] = params.Timespan
	}
	if params != nil && params.Adjusted != "" {
		q["adjusted"] = params.Adjusted
	}
	if params != nil && params.Window != "" {
		q["window"] = params.Window
	}
	if params != nil && params.SeriesType != "" {
		q["series_type"] = params.SeriesType
	}
	if params != nil && params.ExpandUnderlying != "" {
		q["expand_underlying"] = params.ExpandUnderlying
	}
	if params != nil && params.Order != "" {
		q["order"] = params.Order
	}
	if params != nil && params.Limit != "" {
		q["limit"] = params.Limit
	}
	return r.client.get(ctx, "/api/v1/polygon/rsi", q)
}
