// Auto-generated by claw402 codegen — DO NOT EDIT
// Provider: Qwen (通义千问) (qwen)

package claw402

import (
	"context"
	"encoding/json"
)

// QwenQwen provides methods for Qwen qwen endpoints.
type QwenQwen struct {
	client *Client
}

// Chat completions with Qwen3-Max (flagship, most powerful) — $0.01/call
func (r *QwenQwen) ChatMax(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/ai/qwen/chat/max", body)
}

// Chat completions with Qwen-Plus (best value) — $0.005/call
func (r *QwenQwen) ChatPlus(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/ai/qwen/chat/plus", body)
}

// Chat completions with Qwen-Turbo (fast response) — $0.002/call
func (r *QwenQwen) ChatTurbo(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/ai/qwen/chat/turbo", body)
}

// Chat completions with Qwen-Flash (ultra-low latency, cheapest) — $0.002/call
func (r *QwenQwen) ChatFlash(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/ai/qwen/chat/flash", body)
}

// Code generation with Qwen3-Coder-Plus — $0.005/call
func (r *QwenQwen) ChatCoder(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/ai/qwen/chat/coder", body)
}

// Multimodal vision understanding with Qwen-VL-Plus (image + text) — $0.005/call
func (r *QwenQwen) ChatVl(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/ai/qwen/chat/vl", body)
}

// QwenResource provides access to all Qwen (通义千问) API endpoints.
type QwenResource struct {
	client *Client
	Qwen *QwenQwen
}

func newQwenResource(c *Client) *QwenResource {
	return &QwenResource{
		client: c,
		Qwen: &QwenQwen{client: c},
	}
}


