// Auto-generated by claw402 codegen — DO NOT EDIT
// Provider: RootData (rootdata)

package claw402

import (
	"context"
	"encoding/json"
)

// RootdataRootdata provides methods for Rootdata rootdata endpoints.
type RootdataRootdata struct {
	client *Client
}

// RootdataRootdataSearchParams are the query parameters for Search.
type RootdataRootdataSearchParams struct {
	Query string `json:"query,omitempty"`
	PreciseXSearch string `json:"precise_x_search,omitempty"`
}

// Search projects, VCs, and people by keyword. Body: {query: string, precise_x_search?: bool}. Default query: Bitcoin — $0.001/call
func (r *RootdataRootdata) Search(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/search", body)
}

// RootdataRootdataProjectParams are the query parameters for Project.
type RootdataRootdataProjectParams struct {
	ProjectId string `json:"project_id,omitempty"`
	ContractAddress string `json:"contract_address,omitempty"`
	IncludeTeam string `json:"include_team,omitempty"`
	IncludeInvestors string `json:"include_investors,omitempty"`
}

// Get project details. Body: {project_id: int} OR {contract_address: string}. Optional: include_team, include_investors (bool). Find IDs via /search or /id-map — $0.001/call
func (r *RootdataRootdata) Project(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/project", body)
}

// RootdataRootdataOrgParams are the query parameters for Org.
type RootdataRootdataOrgParams struct {
	OrgId string `json:"org_id,omitempty"`
	IncludeTeam string `json:"include_team,omitempty"`
	IncludeInvestments string `json:"include_investments,omitempty"`
}

// Get VC/org details. Body: {org_id: int}. Optional: include_team, include_investments (bool). Find IDs via /search or /id-map — $0.001/call
func (r *RootdataRootdata) Org(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/org", body)
}

// RootdataRootdataPeopleParams are the query parameters for People.
type RootdataRootdataPeopleParams struct {
	PeopleId string `json:"people_id,omitempty"`
}

// Get person profile with X metrics. Body: {people_id: int}. Find IDs via /search or /id-map — $0.001/call
func (r *RootdataRootdata) People(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/people", body)
}

// RootdataRootdataInvestorsParams are the query parameters for Investors.
type RootdataRootdataInvestorsParams struct {
	Page string `json:"page,omitempty"`
	PageSize string `json:"page_size,omitempty"`
}

// Batch list investors. Body: {page?: int, page_size?: int (max 100)}. Defaults: page=1, page_size=10 — $0.001/call
func (r *RootdataRootdata) Investors(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/investors", body)
}

// RootdataRootdataFundingParams are the query parameters for Funding.
type RootdataRootdataFundingParams struct {
	Page string `json:"page,omitempty"`
	PageSize string `json:"page_size,omitempty"`
	StartTime string `json:"start_time,omitempty"`
	EndTime string `json:"end_time,omitempty"`
	MinAmount string `json:"min_amount,omitempty"`
	MaxAmount string `json:"max_amount,omitempty"`
	ProjectId string `json:"project_id,omitempty"`
}

// Batch list funding rounds. Optional filters: start_time, end_time (unix sec), min_amount, max_amount (USD), project_id (int), page, page_size — $0.001/call
func (r *RootdataRootdata) Funding(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/funding", body)
}

// RootdataRootdataChangesParams are the query parameters for Changes.
type RootdataRootdataChangesParams struct {
	BeginTime string `json:"begin_time,omitempty"`
	EndTime string `json:"end_time,omitempty"`
}

// Sync recent data changes. Body: {begin_time: int (unix seconds)}. Optional: end_time. Note: param is begin_time (not start_time) — $0.001/call
func (r *RootdataRootdata) Changes(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/changes", body)
}

// RootdataRootdataHotParams are the query parameters for Hot.
type RootdataRootdataHotParams struct {
	Days string `json:"days,omitempty"`
}

// Top 100 trending projects. Body: {days: int}. Values: 1 = 24h ranking, 7 = 7-day ranking — $0.001/call
func (r *RootdataRootdata) Hot(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/hot", body)
}

// RootdataRootdataHotXParams are the query parameters for HotX.
type RootdataRootdataHotXParams struct {
	Heat string `json:"heat,omitempty"`
	Influence string `json:"influence,omitempty"`
	Followers string `json:"followers,omitempty"`
}

// Trending crypto projects on X. Body: {heat: bool, influence: bool, followers: bool}. Set at least one to true — $0.001/call
func (r *RootdataRootdata) HotX(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/hot-x", body)
}

// RootdataRootdataKolParams are the query parameters for Kol.
type RootdataRootdataKolParams struct {
	RankType string `json:"rank_type,omitempty"`
	Page string `json:"page,omitempty"`
	PageSize string `json:"page_size,omitempty"`
}

// Crypto KOL rankings on X. Body: {rank_type: 'heat' or 'influence'}. Optional: page, page_size — $0.001/call
func (r *RootdataRootdata) Kol(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/kol", body)
}

// RootdataRootdataJobChangesParams are the query parameters for JobChanges.
type RootdataRootdataJobChangesParams struct {
	RecentJoinees string `json:"recent_joinees,omitempty"`
	RecentResignations string `json:"recent_resignations,omitempty"`
}

// Crypto personnel movements. Body: {recent_joinees: bool, recent_resignations: bool}. Set at least one to true — $0.001/call
func (r *RootdataRootdata) JobChanges(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/job-changes", body)
}

// RootdataRootdataNewTokensParams are the query parameters for NewTokens.
type RootdataRootdataNewTokensParams struct {
	Page string `json:"page,omitempty"`
	PageSize string `json:"page_size,omitempty"`
}

// Recently launched token projects. Optional: page, page_size — $0.001/call
func (r *RootdataRootdata) NewTokens(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/new-tokens", body)
}

// RootdataRootdataIdMapParams are the query parameters for IdMap.
type RootdataRootdataIdMapParams struct {
	Type string `json:"type,omitempty"`
}

// Get all entity IDs. Body: {type: int}. Values: 1=projects, 2=VCs, 3=people — $0.001/call
func (r *RootdataRootdata) IdMap(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/id-map", body)
}

// Get all ecosystem IDs and project counts. No parameters required — $0.001/call
func (r *RootdataRootdata) EcosystemMap(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/ecosystem-map", body)
}

// Get all tag/category IDs. No parameters required — $0.001/call
func (r *RootdataRootdata) TagMap(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/tag-map", body)
}

// RootdataRootdataProjectsByEcosystemParams are the query parameters for ProjectsByEcosystem.
type RootdataRootdataProjectsByEcosystemParams struct {
	EcosystemIds string `json:"ecosystem_ids,omitempty"`
	Page string `json:"page,omitempty"`
	PageSize string `json:"page_size,omitempty"`
}

// Projects by ecosystem. Body: {ecosystem_ids: string (comma-separated)}. Get IDs from /ecosystem-map first — $0.001/call
func (r *RootdataRootdata) ProjectsByEcosystem(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/projects-by-ecosystem", body)
}

// RootdataRootdataProjectsByTagParams are the query parameters for ProjectsByTag.
type RootdataRootdataProjectsByTagParams struct {
	TagIds string `json:"tag_ids,omitempty"`
	Page string `json:"page,omitempty"`
	PageSize string `json:"page_size,omitempty"`
}

// Projects by tag. Body: {tag_ids: string (comma-separated)}. Get IDs from /tag-map first — $0.001/call
func (r *RootdataRootdata) ProjectsByTag(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/projects-by-tag", body)
}

// RootdataRootdataTwitterMapParams are the query parameters for TwitterMap.
type RootdataRootdataTwitterMapParams struct {
	Type string `json:"type,omitempty"`
}

// Bulk export X/Twitter data. Body: {type: int}. Values: 1=projects, 2=VCs, 3=people — $0.001/call
func (r *RootdataRootdata) TwitterMap(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/twitter-map", body)
}

// Check API credits balance. No parameters required — $0.001/call
func (r *RootdataRootdata) Credits(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/credits", body)
}

// RootdataResource provides access to all RootData API endpoints.
type RootdataResource struct {
	client *Client
	Rootdata *RootdataRootdata
}

func newRootdataResource(c *Client) *RootdataResource {
	return &RootdataResource{
		client: c,
		Rootdata: &RootdataRootdata{client: c},
	}
}


