// Auto-generated by claw402 codegen — DO NOT EDIT
// Provider: RootData (rootdata)

package claw402

import (
	"context"
	"encoding/json"
)

// RootdataRootdata provides methods for Rootdata rootdata endpoints.
type RootdataRootdata struct {
	client *Client
}

// RootdataRootdataSearchParams are the query parameters for Search.
type RootdataRootdataSearchParams struct {
	Query string `json:"query,omitempty"`
	Page string `json:"page,omitempty"`
	PageSize string `json:"page_size,omitempty"`
}

// Search projects, organizations, and people by keyword — $0.002/call
func (r *RootdataRootdata) Search(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/search", body)
}

// RootdataRootdataProjectParams are the query parameters for Project.
type RootdataRootdataProjectParams struct {
	ProjectId string `json:"project_id,omitempty"`
	ContractAddress string `json:"contract_address,omitempty"`
	IncludeTeam string `json:"include_team,omitempty"`
	IncludeInvestors string `json:"include_investors,omitempty"`
}

// Fetch detailed project info — funding rounds, team, tags. Required: project_id (int) OR contract_address (string) — $0.005/call
func (r *RootdataRootdata) Project(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/project", body)
}

// RootdataRootdataOrgParams are the query parameters for Org.
type RootdataRootdataOrgParams struct {
	OrgId string `json:"org_id,omitempty"`
}

// Fetch organization / VC details. Required: org_id (int) — $0.005/call
func (r *RootdataRootdata) Org(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/org", body)
}

// RootdataRootdataPeopleParams are the query parameters for People.
type RootdataRootdataPeopleParams struct {
	PeopleId string `json:"people_id,omitempty"`
}

// Get individual person profile — career history, investments. Required: people_id (int) — $0.005/call
func (r *RootdataRootdata) People(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/people", body)
}

// RootdataRootdataInvestorsParams are the query parameters for Investors.
type RootdataRootdataInvestorsParams struct {
	Page string `json:"page,omitempty"`
	PageSize string `json:"page_size,omitempty"`
}

// Batch retrieve investor information. Optional: page, page_size — $0.008/call
func (r *RootdataRootdata) Investors(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/investors", body)
}

// RootdataRootdataFundingParams are the query parameters for Funding.
type RootdataRootdataFundingParams struct {
	Page string `json:"page,omitempty"`
	PageSize string `json:"page_size,omitempty"`
}

// Batch fetch funding round information. Optional: page, page_size — $0.008/call
func (r *RootdataRootdata) Funding(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/funding", body)
}

// RootdataRootdataChangesParams are the query parameters for Changes.
type RootdataRootdataChangesParams struct {
	StartTime string `json:"start_time,omitempty"`
	EndTime string `json:"end_time,omitempty"`
}

// Sync data updates within a time range. Required: start_time (unix timestamp, seconds). Optional: end_time — $0.005/call
func (r *RootdataRootdata) Changes(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/changes", body)
}

// RootdataRootdataHotParams are the query parameters for Hot.
type RootdataRootdataHotParams struct {
	Days string `json:"days,omitempty"`
}

// Top 100 trending crypto projects. Required: days (1=24h, 7=7d) — $0.010/call
func (r *RootdataRootdata) Hot(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/hot", body)
}

// RootdataRootdataHotXParams are the query parameters for HotX.
type RootdataRootdataHotXParams struct {
	Heat string `json:"heat,omitempty"`
	Influence string `json:"influence,omitempty"`
	Followers string `json:"followers,omitempty"`
}

// Trending crypto projects on X (Twitter). Required: heat, influence, followers (bool filters) — $0.010/call
func (r *RootdataRootdata) HotX(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/hot-x", body)
}

// RootdataRootdataKolParams are the query parameters for Kol.
type RootdataRootdataKolParams struct {
	RankType string `json:"rank_type,omitempty"`
	Page string `json:"page,omitempty"`
	PageSize string `json:"page_size,omitempty"`
}

// Leading crypto figures on X (Twitter). Required: rank_type (heat|influence). Optional: page, page_size — $0.010/call
func (r *RootdataRootdata) Kol(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/kol", body)
}

// RootdataRootdataJobChangesParams are the query parameters for JobChanges.
type RootdataRootdataJobChangesParams struct {
	RecentJoinees string `json:"recent_joinees,omitempty"`
	RecentResignations string `json:"recent_resignations,omitempty"`
}

// Crypto industry personnel movement. Required: recent_joinees (bool), recent_resignations (bool) — $0.010/call
func (r *RootdataRootdata) JobChanges(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/job-changes", body)
}

// RootdataRootdataNewTokensParams are the query parameters for NewTokens.
type RootdataRootdataNewTokensParams struct {
	Page string `json:"page,omitempty"`
	PageSize string `json:"page_size,omitempty"`
}

// Recently launched token projects. Optional: page, page_size — $0.010/call
func (r *RootdataRootdata) NewTokens(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/new-tokens", body)
}

// RootdataRootdataIdMapParams are the query parameters for IdMap.
type RootdataRootdataIdMapParams struct {
	Type string `json:"type,omitempty"`
}

// Retrieve ID list. Required: type (1=projects, 2=organizations, 3=people) — $0.020/call
func (r *RootdataRootdata) IdMap(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/id-map", body)
}

// Retrieve full ecosystem directory. No required parameters. — $0.020/call
func (r *RootdataRootdata) EcosystemMap(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/ecosystem-map", body)
}

// Access full tag / category mapping. No required parameters. — $0.020/call
func (r *RootdataRootdata) TagMap(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/tag-map", body)
}

// RootdataRootdataProjectsByEcosystemParams are the query parameters for ProjectsByEcosystem.
type RootdataRootdataProjectsByEcosystemParams struct {
	EcosystemIds string `json:"ecosystem_ids,omitempty"`
	Page string `json:"page,omitempty"`
	PageSize string `json:"page_size,omitempty"`
}

// Query projects by ecosystem IDs. Required: ecosystem_ids (string, comma-separated). Optional: page, page_size — $0.015/call
func (r *RootdataRootdata) ProjectsByEcosystem(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/projects-by-ecosystem", body)
}

// RootdataRootdataProjectsByTagParams are the query parameters for ProjectsByTag.
type RootdataRootdataProjectsByTagParams struct {
	TagIds string `json:"tag_ids,omitempty"`
	Page string `json:"page,omitempty"`
	PageSize string `json:"page_size,omitempty"`
}

// Query projects by tag IDs. Required: tag_ids (string, comma-separated). Optional: page, page_size — $0.015/call
func (r *RootdataRootdata) ProjectsByTag(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/projects-by-tag", body)
}

// RootdataRootdataTwitterMapParams are the query parameters for TwitterMap.
type RootdataRootdataTwitterMapParams struct {
	Type string `json:"type,omitempty"`
}

// Bulk export X / Twitter data. Required: type (1=projects, 2=organizations, 3=people) — $0.030/call
func (r *RootdataRootdata) TwitterMap(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/twitter-map", body)
}

// Check remaining API credits balance. No required parameters. — $0.001/call
func (r *RootdataRootdata) Credits(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/crypto/rootdata/credits", body)
}

// RootdataResource provides access to all RootData API endpoints.
type RootdataResource struct {
	client *Client
	Rootdata *RootdataRootdata
}

func newRootdataResource(c *Client) *RootdataResource {
	return &RootdataResource{
		client: c,
		Rootdata: &RootdataRootdata{client: c},
	}
}


