// Auto-generated by claw402 codegen — DO NOT EDIT
// Provider: Tushare Pro (tushare)

package claw402

import (
	"context"
	"encoding/json"
)

// TushareCn provides methods for Tushare cn endpoints.
type TushareCn struct {
	client *Client
}

// TushareCnDailyParams are the query parameters for Daily.
type TushareCnDailyParams struct {
	TsCode string `json:"ts_code,omitempty"`
	TradeDate string `json:"trade_date,omitempty"`
	StartDate string `json:"start_date,omitempty"`
	EndDate string `json:"end_date,omitempty"`
}

// A-share daily OHLCV + price change — $0.001/call
func (r *TushareCn) Daily(ctx context.Context, params *TushareCnDailyParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.TsCode != "" {
		q["ts_code"] = params.TsCode
	}
	if params != nil && params.TradeDate != "" {
		q["trade_date"] = params.TradeDate
	}
	if params != nil && params.StartDate != "" {
		q["start_date"] = params.StartDate
	}
	if params != nil && params.EndDate != "" {
		q["end_date"] = params.EndDate
	}
	return r.client.get(ctx, "/api/v1/stocks/cn/daily", q)
}

// TushareCnWeeklyParams are the query parameters for Weekly.
type TushareCnWeeklyParams struct {
	TsCode string `json:"ts_code,omitempty"`
	TradeDate string `json:"trade_date,omitempty"`
	StartDate string `json:"start_date,omitempty"`
	EndDate string `json:"end_date,omitempty"`
}

// A-share weekly OHLCV — $0.001/call
func (r *TushareCn) Weekly(ctx context.Context, params *TushareCnWeeklyParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.TsCode != "" {
		q["ts_code"] = params.TsCode
	}
	if params != nil && params.TradeDate != "" {
		q["trade_date"] = params.TradeDate
	}
	if params != nil && params.StartDate != "" {
		q["start_date"] = params.StartDate
	}
	if params != nil && params.EndDate != "" {
		q["end_date"] = params.EndDate
	}
	return r.client.get(ctx, "/api/v1/stocks/cn/weekly", q)
}

// TushareCnMonthlyParams are the query parameters for Monthly.
type TushareCnMonthlyParams struct {
	TsCode string `json:"ts_code,omitempty"`
	TradeDate string `json:"trade_date,omitempty"`
	StartDate string `json:"start_date,omitempty"`
	EndDate string `json:"end_date,omitempty"`
}

// A-share monthly OHLCV — $0.001/call
func (r *TushareCn) Monthly(ctx context.Context, params *TushareCnMonthlyParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.TsCode != "" {
		q["ts_code"] = params.TsCode
	}
	if params != nil && params.TradeDate != "" {
		q["trade_date"] = params.TradeDate
	}
	if params != nil && params.StartDate != "" {
		q["start_date"] = params.StartDate
	}
	if params != nil && params.EndDate != "" {
		q["end_date"] = params.EndDate
	}
	return r.client.get(ctx, "/api/v1/stocks/cn/monthly", q)
}

// TushareCnDailyBasicParams are the query parameters for DailyBasic.
type TushareCnDailyBasicParams struct {
	TsCode string `json:"ts_code,omitempty"`
	TradeDate string `json:"trade_date,omitempty"`
	StartDate string `json:"start_date,omitempty"`
	EndDate string `json:"end_date,omitempty"`
}

// Daily valuation metrics: PE, PB, turnover rate, market cap — $0.001/call
func (r *TushareCn) DailyBasic(ctx context.Context, params *TushareCnDailyBasicParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.TsCode != "" {
		q["ts_code"] = params.TsCode
	}
	if params != nil && params.TradeDate != "" {
		q["trade_date"] = params.TradeDate
	}
	if params != nil && params.StartDate != "" {
		q["start_date"] = params.StartDate
	}
	if params != nil && params.EndDate != "" {
		q["end_date"] = params.EndDate
	}
	return r.client.get(ctx, "/api/v1/stocks/cn/daily-basic", q)
}

// TushareCnStockBasicParams are the query parameters for StockBasic.
type TushareCnStockBasicParams struct {
	Exchange string `json:"exchange,omitempty"`
	ListStatus string `json:"list_status,omitempty"`
	IsHs string `json:"is_hs,omitempty"`
}

// A-share stock list: code, name, listing date, industry — $0.001/call
func (r *TushareCn) StockBasic(ctx context.Context, params *TushareCnStockBasicParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Exchange != "" {
		q["exchange"] = params.Exchange
	}
	if params != nil && params.ListStatus != "" {
		q["list_status"] = params.ListStatus
	}
	if params != nil && params.IsHs != "" {
		q["is_hs"] = params.IsHs
	}
	return r.client.get(ctx, "/api/v1/stocks/cn/stock-basic", q)
}

// TushareCnTradeCalParams are the query parameters for TradeCal.
type TushareCnTradeCalParams struct {
	Exchange string `json:"exchange,omitempty"`
	StartDate string `json:"start_date,omitempty"`
	EndDate string `json:"end_date,omitempty"`
	IsOpen string `json:"is_open,omitempty"`
}

// Trading calendar — open/closed market days — $0.001/call
func (r *TushareCn) TradeCal(ctx context.Context, params *TushareCnTradeCalParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Exchange != "" {
		q["exchange"] = params.Exchange
	}
	if params != nil && params.StartDate != "" {
		q["start_date"] = params.StartDate
	}
	if params != nil && params.EndDate != "" {
		q["end_date"] = params.EndDate
	}
	if params != nil && params.IsOpen != "" {
		q["is_open"] = params.IsOpen
	}
	return r.client.get(ctx, "/api/v1/stocks/cn/trade-cal", q)
}

// TushareCnIncomeParams are the query parameters for Income.
type TushareCnIncomeParams struct {
	TsCode string `json:"ts_code,omitempty"`
	AnnDate string `json:"ann_date,omitempty"`
	StartDate string `json:"start_date,omitempty"`
	EndDate string `json:"end_date,omitempty"`
	Period string `json:"period,omitempty"`
	ReportType string `json:"report_type,omitempty"`
}

// Income statement: revenue, net profit, gross margin — $0.001/call
func (r *TushareCn) Income(ctx context.Context, params *TushareCnIncomeParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.TsCode != "" {
		q["ts_code"] = params.TsCode
	}
	if params != nil && params.AnnDate != "" {
		q["ann_date"] = params.AnnDate
	}
	if params != nil && params.StartDate != "" {
		q["start_date"] = params.StartDate
	}
	if params != nil && params.EndDate != "" {
		q["end_date"] = params.EndDate
	}
	if params != nil && params.Period != "" {
		q["period"] = params.Period
	}
	if params != nil && params.ReportType != "" {
		q["report_type"] = params.ReportType
	}
	return r.client.get(ctx, "/api/v1/stocks/cn/income", q)
}

// TushareCnBalanceSheetParams are the query parameters for BalanceSheet.
type TushareCnBalanceSheetParams struct {
	TsCode string `json:"ts_code,omitempty"`
	AnnDate string `json:"ann_date,omitempty"`
	StartDate string `json:"start_date,omitempty"`
	EndDate string `json:"end_date,omitempty"`
	Period string `json:"period,omitempty"`
	ReportType string `json:"report_type,omitempty"`
}

// Balance sheet: assets, liabilities, equity — $0.001/call
func (r *TushareCn) BalanceSheet(ctx context.Context, params *TushareCnBalanceSheetParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.TsCode != "" {
		q["ts_code"] = params.TsCode
	}
	if params != nil && params.AnnDate != "" {
		q["ann_date"] = params.AnnDate
	}
	if params != nil && params.StartDate != "" {
		q["start_date"] = params.StartDate
	}
	if params != nil && params.EndDate != "" {
		q["end_date"] = params.EndDate
	}
	if params != nil && params.Period != "" {
		q["period"] = params.Period
	}
	if params != nil && params.ReportType != "" {
		q["report_type"] = params.ReportType
	}
	return r.client.get(ctx, "/api/v1/stocks/cn/balance-sheet", q)
}

// TushareCnCashFlowParams are the query parameters for CashFlow.
type TushareCnCashFlowParams struct {
	TsCode string `json:"ts_code,omitempty"`
	AnnDate string `json:"ann_date,omitempty"`
	StartDate string `json:"start_date,omitempty"`
	EndDate string `json:"end_date,omitempty"`
	Period string `json:"period,omitempty"`
	ReportType string `json:"report_type,omitempty"`
}

// Cash flow statement: operating, investing, financing — $0.001/call
func (r *TushareCn) CashFlow(ctx context.Context, params *TushareCnCashFlowParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.TsCode != "" {
		q["ts_code"] = params.TsCode
	}
	if params != nil && params.AnnDate != "" {
		q["ann_date"] = params.AnnDate
	}
	if params != nil && params.StartDate != "" {
		q["start_date"] = params.StartDate
	}
	if params != nil && params.EndDate != "" {
		q["end_date"] = params.EndDate
	}
	if params != nil && params.Period != "" {
		q["period"] = params.Period
	}
	if params != nil && params.ReportType != "" {
		q["report_type"] = params.ReportType
	}
	return r.client.get(ctx, "/api/v1/stocks/cn/cash-flow", q)
}

// TushareCnDividendParams are the query parameters for Dividend.
type TushareCnDividendParams struct {
	TsCode string `json:"ts_code,omitempty"`
	AnnDate string `json:"ann_date,omitempty"`
	RecordDate string `json:"record_date,omitempty"`
	ExDate string `json:"ex_date,omitempty"`
	ImpAnnDate string `json:"imp_ann_date,omitempty"`
}

// Historical dividends and rights offerings — $0.001/call
func (r *TushareCn) Dividend(ctx context.Context, params *TushareCnDividendParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.TsCode != "" {
		q["ts_code"] = params.TsCode
	}
	if params != nil && params.AnnDate != "" {
		q["ann_date"] = params.AnnDate
	}
	if params != nil && params.RecordDate != "" {
		q["record_date"] = params.RecordDate
	}
	if params != nil && params.ExDate != "" {
		q["ex_date"] = params.ExDate
	}
	if params != nil && params.ImpAnnDate != "" {
		q["imp_ann_date"] = params.ImpAnnDate
	}
	return r.client.get(ctx, "/api/v1/stocks/cn/dividend", q)
}

// TushareCnNorthboundParams are the query parameters for Northbound.
type TushareCnNorthboundParams struct {
	TradeDate string `json:"trade_date,omitempty"`
	StartDate string `json:"start_date,omitempty"`
	EndDate string `json:"end_date,omitempty"`
}

// Northbound capital flow (Stock Connect daily net inflow) — $0.001/call
func (r *TushareCn) Northbound(ctx context.Context, params *TushareCnNorthboundParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.TradeDate != "" {
		q["trade_date"] = params.TradeDate
	}
	if params != nil && params.StartDate != "" {
		q["start_date"] = params.StartDate
	}
	if params != nil && params.EndDate != "" {
		q["end_date"] = params.EndDate
	}
	return r.client.get(ctx, "/api/v1/stocks/cn/northbound", q)
}

// TushareCnMoneyflowParams are the query parameters for Moneyflow.
type TushareCnMoneyflowParams struct {
	TsCode string `json:"ts_code,omitempty"`
	TradeDate string `json:"trade_date,omitempty"`
	StartDate string `json:"start_date,omitempty"`
	EndDate string `json:"end_date,omitempty"`
}

// Individual stock capital flow: big money vs. retail net inflow — $0.001/call
func (r *TushareCn) Moneyflow(ctx context.Context, params *TushareCnMoneyflowParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.TsCode != "" {
		q["ts_code"] = params.TsCode
	}
	if params != nil && params.TradeDate != "" {
		q["trade_date"] = params.TradeDate
	}
	if params != nil && params.StartDate != "" {
		q["start_date"] = params.StartDate
	}
	if params != nil && params.EndDate != "" {
		q["end_date"] = params.EndDate
	}
	return r.client.get(ctx, "/api/v1/stocks/cn/moneyflow", q)
}

// TushareCnMarginParams are the query parameters for Margin.
type TushareCnMarginParams struct {
	TradeDate string `json:"trade_date,omitempty"`
	StartDate string `json:"start_date,omitempty"`
	EndDate string `json:"end_date,omitempty"`
	ExchangeId string `json:"exchange_id,omitempty"`
}

// Margin trading summary: total margin balance — $0.001/call
func (r *TushareCn) Margin(ctx context.Context, params *TushareCnMarginParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.TradeDate != "" {
		q["trade_date"] = params.TradeDate
	}
	if params != nil && params.StartDate != "" {
		q["start_date"] = params.StartDate
	}
	if params != nil && params.EndDate != "" {
		q["end_date"] = params.EndDate
	}
	if params != nil && params.ExchangeId != "" {
		q["exchange_id"] = params.ExchangeId
	}
	return r.client.get(ctx, "/api/v1/stocks/cn/margin", q)
}

// TushareCnMarginDetailParams are the query parameters for MarginDetail.
type TushareCnMarginDetailParams struct {
	TsCode string `json:"ts_code,omitempty"`
	TradeDate string `json:"trade_date,omitempty"`
	StartDate string `json:"start_date,omitempty"`
	EndDate string `json:"end_date,omitempty"`
}

// Per-stock margin trading detail (rzye, rqye) — $0.001/call
func (r *TushareCn) MarginDetail(ctx context.Context, params *TushareCnMarginDetailParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.TsCode != "" {
		q["ts_code"] = params.TsCode
	}
	if params != nil && params.TradeDate != "" {
		q["trade_date"] = params.TradeDate
	}
	if params != nil && params.StartDate != "" {
		q["start_date"] = params.StartDate
	}
	if params != nil && params.EndDate != "" {
		q["end_date"] = params.EndDate
	}
	return r.client.get(ctx, "/api/v1/stocks/cn/margin-detail", q)
}

// TushareCnTopListParams are the query parameters for TopList.
type TushareCnTopListParams struct {
	TradeDate string `json:"trade_date,omitempty"`
	TsCode string `json:"ts_code,omitempty"`
}

// Dragon-Tiger list — notable institutional activity stocks — $0.001/call
func (r *TushareCn) TopList(ctx context.Context, params *TushareCnTopListParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.TradeDate != "" {
		q["trade_date"] = params.TradeDate
	}
	if params != nil && params.TsCode != "" {
		q["ts_code"] = params.TsCode
	}
	return r.client.get(ctx, "/api/v1/stocks/cn/top-list", q)
}

// TushareCnTopInstParams are the query parameters for TopInst.
type TushareCnTopInstParams struct {
	TradeDate string `json:"trade_date,omitempty"`
	TsCode string `json:"ts_code,omitempty"`
}

// Dragon-Tiger institutional seat buy/sell details — $0.001/call
func (r *TushareCn) TopInst(ctx context.Context, params *TushareCnTopInstParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.TradeDate != "" {
		q["trade_date"] = params.TradeDate
	}
	if params != nil && params.TsCode != "" {
		q["ts_code"] = params.TsCode
	}
	return r.client.get(ctx, "/api/v1/stocks/cn/top-inst", q)
}

// TushareResource provides access to all Tushare Pro API endpoints.
type TushareResource struct {
	client *Client
	Cn *TushareCn
}

func newTushareResource(c *Client) *TushareResource {
	return &TushareResource{
		client: c,
		Cn: &TushareCn{client: c},
	}
}


