// Auto-generated by claw402 codegen — DO NOT EDIT
// Provider: Twelve Data (twelvedata)

package claw402

import (
	"context"
	"encoding/json"
)

// TwelvedataTimeSeries provides methods for Twelvedata timeSeries endpoints.
type TwelvedataTimeSeries struct {
	client *Client
}

// Complex query: multiple symbols + indicators in one request — $0.005/call
func (r *TwelvedataTimeSeries) Complex(ctx context.Context, body map[string]interface{}) (json.RawMessage, error) {
	return r.client.post(ctx, "/api/v1/twelvedata/time-series/complex", body)
}

// TwelvedataIndicator provides methods for Twelvedata indicator endpoints.
type TwelvedataIndicator struct {
	client *Client
}

// TwelvedataIndicatorSmaParams are the query parameters for Sma.
type TwelvedataIndicatorSmaParams struct {
	Symbol string `json:"symbol,omitempty"`
	Interval string `json:"interval,omitempty"`
	TimePeriod string `json:"time_period,omitempty"`
	Outputsize string `json:"outputsize,omitempty"`
}

// Simple Moving Average (SMA) — $0.002/call
func (r *TwelvedataIndicator) Sma(ctx context.Context, params *TwelvedataIndicatorSmaParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	if params != nil && params.Interval != "" {
		q["interval"] = params.Interval
	}
	if params != nil && params.TimePeriod != "" {
		q["time_period"] = params.TimePeriod
	}
	if params != nil && params.Outputsize != "" {
		q["outputsize"] = params.Outputsize
	}
	return r.client.get(ctx, "/api/v1/twelvedata/indicator/sma", q)
}

// TwelvedataIndicatorEmaParams are the query parameters for Ema.
type TwelvedataIndicatorEmaParams struct {
	Symbol string `json:"symbol,omitempty"`
	Interval string `json:"interval,omitempty"`
	TimePeriod string `json:"time_period,omitempty"`
	Outputsize string `json:"outputsize,omitempty"`
}

// Exponential Moving Average (EMA) — $0.002/call
func (r *TwelvedataIndicator) Ema(ctx context.Context, params *TwelvedataIndicatorEmaParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	if params != nil && params.Interval != "" {
		q["interval"] = params.Interval
	}
	if params != nil && params.TimePeriod != "" {
		q["time_period"] = params.TimePeriod
	}
	if params != nil && params.Outputsize != "" {
		q["outputsize"] = params.Outputsize
	}
	return r.client.get(ctx, "/api/v1/twelvedata/indicator/ema", q)
}

// TwelvedataIndicatorRsiParams are the query parameters for Rsi.
type TwelvedataIndicatorRsiParams struct {
	Symbol string `json:"symbol,omitempty"`
	Interval string `json:"interval,omitempty"`
	TimePeriod string `json:"time_period,omitempty"`
	Outputsize string `json:"outputsize,omitempty"`
}

// Relative Strength Index (RSI) — $0.002/call
func (r *TwelvedataIndicator) Rsi(ctx context.Context, params *TwelvedataIndicatorRsiParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	if params != nil && params.Interval != "" {
		q["interval"] = params.Interval
	}
	if params != nil && params.TimePeriod != "" {
		q["time_period"] = params.TimePeriod
	}
	if params != nil && params.Outputsize != "" {
		q["outputsize"] = params.Outputsize
	}
	return r.client.get(ctx, "/api/v1/twelvedata/indicator/rsi", q)
}

// TwelvedataIndicatorMacdParams are the query parameters for Macd.
type TwelvedataIndicatorMacdParams struct {
	Symbol string `json:"symbol,omitempty"`
	Interval string `json:"interval,omitempty"`
	Outputsize string `json:"outputsize,omitempty"`
}

// Moving Average Convergence Divergence (MACD) — $0.002/call
func (r *TwelvedataIndicator) Macd(ctx context.Context, params *TwelvedataIndicatorMacdParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	if params != nil && params.Interval != "" {
		q["interval"] = params.Interval
	}
	if params != nil && params.Outputsize != "" {
		q["outputsize"] = params.Outputsize
	}
	return r.client.get(ctx, "/api/v1/twelvedata/indicator/macd", q)
}

// TwelvedataIndicatorBbandsParams are the query parameters for Bbands.
type TwelvedataIndicatorBbandsParams struct {
	Symbol string `json:"symbol,omitempty"`
	Interval string `json:"interval,omitempty"`
	TimePeriod string `json:"time_period,omitempty"`
	Outputsize string `json:"outputsize,omitempty"`
}

// Bollinger Bands — $0.002/call
func (r *TwelvedataIndicator) Bbands(ctx context.Context, params *TwelvedataIndicatorBbandsParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	if params != nil && params.Interval != "" {
		q["interval"] = params.Interval
	}
	if params != nil && params.TimePeriod != "" {
		q["time_period"] = params.TimePeriod
	}
	if params != nil && params.Outputsize != "" {
		q["outputsize"] = params.Outputsize
	}
	return r.client.get(ctx, "/api/v1/twelvedata/indicator/bbands", q)
}

// TwelvedataIndicatorAtrParams are the query parameters for Atr.
type TwelvedataIndicatorAtrParams struct {
	Symbol string `json:"symbol,omitempty"`
	Interval string `json:"interval,omitempty"`
	TimePeriod string `json:"time_period,omitempty"`
	Outputsize string `json:"outputsize,omitempty"`
}

// Average True Range (ATR) — $0.002/call
func (r *TwelvedataIndicator) Atr(ctx context.Context, params *TwelvedataIndicatorAtrParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	if params != nil && params.Interval != "" {
		q["interval"] = params.Interval
	}
	if params != nil && params.TimePeriod != "" {
		q["time_period"] = params.TimePeriod
	}
	if params != nil && params.Outputsize != "" {
		q["outputsize"] = params.Outputsize
	}
	return r.client.get(ctx, "/api/v1/twelvedata/indicator/atr", q)
}

// TwelvedataMetals provides methods for Twelvedata metals endpoints.
type TwelvedataMetals struct {
	client *Client
}

// TwelvedataMetalsPriceParams are the query parameters for Price.
type TwelvedataMetalsPriceParams struct {
	Symbol string `json:"symbol,omitempty"`
}

// Precious metals real-time price (XAU/USD, XAG/USD, etc.) — $0.001/call
func (r *TwelvedataMetals) Price(ctx context.Context, params *TwelvedataMetalsPriceParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	return r.client.get(ctx, "/api/v1/twelvedata/metals/price", q)
}

// TwelvedataMetalsTimeSeriesParams are the query parameters for TimeSeries.
type TwelvedataMetalsTimeSeriesParams struct {
	Symbol string `json:"symbol,omitempty"`
	Interval string `json:"interval,omitempty"`
	Outputsize string `json:"outputsize,omitempty"`
	StartDate string `json:"start_date,omitempty"`
	EndDate string `json:"end_date,omitempty"`
}

// Precious metals historical bars — $0.002/call
func (r *TwelvedataMetals) TimeSeries(ctx context.Context, params *TwelvedataMetalsTimeSeriesParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	if params != nil && params.Interval != "" {
		q["interval"] = params.Interval
	}
	if params != nil && params.Outputsize != "" {
		q["outputsize"] = params.Outputsize
	}
	if params != nil && params.StartDate != "" {
		q["start_date"] = params.StartDate
	}
	if params != nil && params.EndDate != "" {
		q["end_date"] = params.EndDate
	}
	return r.client.get(ctx, "/api/v1/twelvedata/metals/time-series", q)
}

// TwelvedataIndices provides methods for Twelvedata indices endpoints.
type TwelvedataIndices struct {
	client *Client
}

// TwelvedataIndicesListParams are the query parameters for List.
type TwelvedataIndicesListParams struct {
	Country string `json:"country,omitempty"`
}

// List of global indices — $0.001/call
func (r *TwelvedataIndices) List(ctx context.Context, params *TwelvedataIndicesListParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Country != "" {
		q["country"] = params.Country
	}
	return r.client.get(ctx, "/api/v1/twelvedata/indices/list", q)
}

// TwelvedataIndicesQuoteParams are the query parameters for Quote.
type TwelvedataIndicesQuoteParams struct {
	Symbol string `json:"symbol,omitempty"`
	Interval string `json:"interval,omitempty"`
}

// Index detailed quote (S&P 500, Hang Seng, Nikkei, etc.) — $0.002/call
func (r *TwelvedataIndices) Quote(ctx context.Context, params *TwelvedataIndicesQuoteParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	if params != nil && params.Interval != "" {
		q["interval"] = params.Interval
	}
	return r.client.get(ctx, "/api/v1/twelvedata/indices/quote", q)
}

// TwelvedataResource provides access to all Twelve Data API endpoints.
type TwelvedataResource struct {
	client *Client
	TimeSeries *TwelvedataTimeSeries
	Indicator *TwelvedataIndicator
	Metals *TwelvedataMetals
	Indices *TwelvedataIndices
}

func newTwelvedataResource(c *Client) *TwelvedataResource {
	return &TwelvedataResource{
		client: c,
		TimeSeries: &TwelvedataTimeSeries{client: c},
		Indicator: &TwelvedataIndicator{client: c},
		Metals: &TwelvedataMetals{client: c},
		Indices: &TwelvedataIndices{client: c},
	}
}

// TwelvedataPriceParams are the query parameters for Price.
type TwelvedataPriceParams struct {
	Symbol string `json:"symbol,omitempty"`
}

// Real-time price for forex, metals, indices, or crypto — $0.001/call
func (r *TwelvedataResource) Price(ctx context.Context, params *TwelvedataPriceParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	return r.client.get(ctx, "/api/v1/twelvedata/price", q)
}

// TwelvedataQuoteParams are the query parameters for Quote.
type TwelvedataQuoteParams struct {
	Symbol string `json:"symbol,omitempty"`
	Interval string `json:"interval,omitempty"`
}

// Detailed quote with OHLC, volume, 52-week high/low, etc. — $0.002/call
func (r *TwelvedataResource) Quote(ctx context.Context, params *TwelvedataQuoteParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	if params != nil && params.Interval != "" {
		q["interval"] = params.Interval
	}
	return r.client.get(ctx, "/api/v1/twelvedata/quote", q)
}

// TwelvedataEodParams are the query parameters for Eod.
type TwelvedataEodParams struct {
	Symbol string `json:"symbol,omitempty"`
}

// End-of-day closing price — $0.001/call
func (r *TwelvedataResource) Eod(ctx context.Context, params *TwelvedataEodParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	return r.client.get(ctx, "/api/v1/twelvedata/eod", q)
}

// TwelvedataExchangeRateParams are the query parameters for ExchangeRate.
type TwelvedataExchangeRateParams struct {
	Symbol string `json:"symbol,omitempty"`
}

// Currency exchange rate (e.g. USD/CNY, EUR/JPY) — $0.001/call
func (r *TwelvedataResource) ExchangeRate(ctx context.Context, params *TwelvedataExchangeRateParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	return r.client.get(ctx, "/api/v1/twelvedata/exchange-rate", q)
}

// TwelvedataForexPairsParams are the query parameters for ForexPairs.
type TwelvedataForexPairsParams struct {
	CurrencyBase string `json:"currency_base,omitempty"`
	CurrencyQuote string `json:"currency_quote,omitempty"`
}

// List of available forex pairs — $0.001/call
func (r *TwelvedataResource) ForexPairs(ctx context.Context, params *TwelvedataForexPairsParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.CurrencyBase != "" {
		q["currency_base"] = params.CurrencyBase
	}
	if params != nil && params.CurrencyQuote != "" {
		q["currency_quote"] = params.CurrencyQuote
	}
	return r.client.get(ctx, "/api/v1/twelvedata/forex-pairs", q)
}

// TwelvedataGetTimeSeriesParams are the query parameters for GetTimeSeries.
type TwelvedataGetTimeSeriesParams struct {
	Symbol string `json:"symbol,omitempty"`
	Interval string `json:"interval,omitempty"`
	Outputsize string `json:"outputsize,omitempty"`
	StartDate string `json:"start_date,omitempty"`
	EndDate string `json:"end_date,omitempty"`
}

// Historical OHLCV bars (1min to 1month intervals) — $0.002/call
func (r *TwelvedataResource) GetTimeSeries(ctx context.Context, params *TwelvedataGetTimeSeriesParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Symbol != "" {
		q["symbol"] = params.Symbol
	}
	if params != nil && params.Interval != "" {
		q["interval"] = params.Interval
	}
	if params != nil && params.Outputsize != "" {
		q["outputsize"] = params.Outputsize
	}
	if params != nil && params.StartDate != "" {
		q["start_date"] = params.StartDate
	}
	if params != nil && params.EndDate != "" {
		q["end_date"] = params.EndDate
	}
	return r.client.get(ctx, "/api/v1/twelvedata/time-series", q)
}

// TwelvedataEconomicCalendarParams are the query parameters for EconomicCalendar.
type TwelvedataEconomicCalendarParams struct {
	Country string `json:"country,omitempty"`
	StartDate string `json:"start_date,omitempty"`
	EndDate string `json:"end_date,omitempty"`
	Importance string `json:"importance,omitempty"`
}

// Global economic calendar (NFP, CPI, rate decisions, etc.) — $0.003/call
func (r *TwelvedataResource) EconomicCalendar(ctx context.Context, params *TwelvedataEconomicCalendarParams) (json.RawMessage, error) {
	q := map[string]string{}
	if params != nil && params.Country != "" {
		q["country"] = params.Country
	}
	if params != nil && params.StartDate != "" {
		q["start_date"] = params.StartDate
	}
	if params != nil && params.EndDate != "" {
		q["end_date"] = params.EndDate
	}
	if params != nil && params.Importance != "" {
		q["importance"] = params.Importance
	}
	return r.client.get(ctx, "/api/v1/twelvedata/economic-calendar", q)
}
